// This file is auto-generated by @hey-api/openapi-ts

import type { CurrentUserForLoginResponse, DeliveryResponse, GetCompletedSessionSummariesResponse, GetLiveSessionDataResponse, GetLiveSessionHistoryResponse, GetNonRivianUserSessionResponse, GetUserInfoResponse, GetVehicleLastConnectionResponse, GetVehicleStateResponse } from './types.gen.js';

const timestampedValueSchemaResponseTransformer = (data: any) => {
    if (data.timeStamp) {
        data.timeStamp = new Date(data.timeStamp);
    }
    return data;
};

const vehicleStateSchemaResponseTransformer = (data: any) => {
    if (data.gnssLocation) {
        if (data.gnssLocation.timeStamp) {
            data.gnssLocation.timeStamp = new Date(data.gnssLocation.timeStamp);
        }
    }
    if (data.gnssSpeed) {
        data.gnssSpeed = timestampedValueSchemaResponseTransformer(data.gnssSpeed);
    }
    if (data.gnssAltitude) {
        data.gnssAltitude = timestampedValueSchemaResponseTransformer(data.gnssAltitude);
    }
    if (data.gnssError) {
        if (data.gnssError.timeStamp) {
            data.gnssError.timeStamp = new Date(data.gnssError.timeStamp);
        }
    }
    if (data.alarmSoundStatus) {
        data.alarmSoundStatus = timestampedValueSchemaResponseTransformer(data.alarmSoundStatus);
    }
    if (data.timeToEndOfCharge) {
        data.timeToEndOfCharge = timestampedValueSchemaResponseTransformer(data.timeToEndOfCharge);
    }
    if (data.doorFrontLeftLocked) {
        data.doorFrontLeftLocked = timestampedValueSchemaResponseTransformer(data.doorFrontLeftLocked);
    }
    if (data.doorFrontLeftClosed) {
        data.doorFrontLeftClosed = timestampedValueSchemaResponseTransformer(data.doorFrontLeftClosed);
    }
    if (data.doorFrontRightLocked) {
        data.doorFrontRightLocked = timestampedValueSchemaResponseTransformer(data.doorFrontRightLocked);
    }
    if (data.doorFrontRightClosed) {
        data.doorFrontRightClosed = timestampedValueSchemaResponseTransformer(data.doorFrontRightClosed);
    }
    if (data.doorRearLeftLocked) {
        data.doorRearLeftLocked = timestampedValueSchemaResponseTransformer(data.doorRearLeftLocked);
    }
    if (data.doorRearLeftClosed) {
        data.doorRearLeftClosed = timestampedValueSchemaResponseTransformer(data.doorRearLeftClosed);
    }
    if (data.doorRearRightLocked) {
        data.doorRearRightLocked = timestampedValueSchemaResponseTransformer(data.doorRearRightLocked);
    }
    if (data.doorRearRightClosed) {
        data.doorRearRightClosed = timestampedValueSchemaResponseTransformer(data.doorRearRightClosed);
    }
    if (data.windowFrontLeftClosed) {
        data.windowFrontLeftClosed = timestampedValueSchemaResponseTransformer(data.windowFrontLeftClosed);
    }
    if (data.windowFrontRightClosed) {
        data.windowFrontRightClosed = timestampedValueSchemaResponseTransformer(data.windowFrontRightClosed);
    }
    if (data.windowFrontLeftCalibrated) {
        data.windowFrontLeftCalibrated = timestampedValueSchemaResponseTransformer(data.windowFrontLeftCalibrated);
    }
    if (data.windowFrontRightCalibrated) {
        data.windowFrontRightCalibrated = timestampedValueSchemaResponseTransformer(data.windowFrontRightCalibrated);
    }
    if (data.windowRearLeftCalibrated) {
        data.windowRearLeftCalibrated = timestampedValueSchemaResponseTransformer(data.windowRearLeftCalibrated);
    }
    if (data.windowRearRightCalibrated) {
        data.windowRearRightCalibrated = timestampedValueSchemaResponseTransformer(data.windowRearRightCalibrated);
    }
    if (data.windowRearLeftClosed) {
        data.windowRearLeftClosed = timestampedValueSchemaResponseTransformer(data.windowRearLeftClosed);
    }
    if (data.windowRearRightClosed) {
        data.windowRearRightClosed = timestampedValueSchemaResponseTransformer(data.windowRearRightClosed);
    }
    if (data.closureFrunkLocked) {
        data.closureFrunkLocked = timestampedValueSchemaResponseTransformer(data.closureFrunkLocked);
    }
    if (data.closureFrunkClosed) {
        data.closureFrunkClosed = timestampedValueSchemaResponseTransformer(data.closureFrunkClosed);
    }
    if (data.closureFrunkNextAction) {
        data.closureFrunkNextAction = timestampedValueSchemaResponseTransformer(data.closureFrunkNextAction);
    }
    if (data.closureLiftgateLocked) {
        data.closureLiftgateLocked = timestampedValueSchemaResponseTransformer(data.closureLiftgateLocked);
    }
    if (data.closureLiftgateClosed) {
        data.closureLiftgateClosed = timestampedValueSchemaResponseTransformer(data.closureLiftgateClosed);
    }
    if (data.closureLiftgateNextAction) {
        data.closureLiftgateNextAction = timestampedValueSchemaResponseTransformer(data.closureLiftgateNextAction);
    }
    if (data.closureSideBinLeftLocked) {
        data.closureSideBinLeftLocked = timestampedValueSchemaResponseTransformer(data.closureSideBinLeftLocked);
    }
    if (data.closureSideBinLeftClosed) {
        data.closureSideBinLeftClosed = timestampedValueSchemaResponseTransformer(data.closureSideBinLeftClosed);
    }
    if (data.closureSideBinRightLocked) {
        data.closureSideBinRightLocked = timestampedValueSchemaResponseTransformer(data.closureSideBinRightLocked);
    }
    if (data.closureSideBinLeftNextAction) {
        data.closureSideBinLeftNextAction = timestampedValueSchemaResponseTransformer(data.closureSideBinLeftNextAction);
    }
    if (data.closureSideBinRightClosed) {
        data.closureSideBinRightClosed = timestampedValueSchemaResponseTransformer(data.closureSideBinRightClosed);
    }
    if (data.closureSideBinRightNextAction) {
        data.closureSideBinRightNextAction = timestampedValueSchemaResponseTransformer(data.closureSideBinRightNextAction);
    }
    if (data.closureTailgateLocked) {
        data.closureTailgateLocked = timestampedValueSchemaResponseTransformer(data.closureTailgateLocked);
    }
    if (data.closureTailgateClosed) {
        data.closureTailgateClosed = timestampedValueSchemaResponseTransformer(data.closureTailgateClosed);
    }
    if (data.closureTailgateNextAction) {
        data.closureTailgateNextAction = timestampedValueSchemaResponseTransformer(data.closureTailgateNextAction);
    }
    if (data.closureTonneauLocked) {
        data.closureTonneauLocked = timestampedValueSchemaResponseTransformer(data.closureTonneauLocked);
    }
    if (data.closureTonneauClosed) {
        data.closureTonneauClosed = timestampedValueSchemaResponseTransformer(data.closureTonneauClosed);
    }
    if (data.gearGuardLocked) {
        data.gearGuardLocked = timestampedValueSchemaResponseTransformer(data.gearGuardLocked);
    }
    if (data.wiperFluidState) {
        data.wiperFluidState = timestampedValueSchemaResponseTransformer(data.wiperFluidState);
    }
    if (data.powerState) {
        data.powerState = timestampedValueSchemaResponseTransformer(data.powerState);
    }
    if (data.batteryHvThermalEventPropagation) {
        data.batteryHvThermalEventPropagation = timestampedValueSchemaResponseTransformer(data.batteryHvThermalEventPropagation);
    }
    if (data.twelveVoltBatteryHealth) {
        data.twelveVoltBatteryHealth = timestampedValueSchemaResponseTransformer(data.twelveVoltBatteryHealth);
    }
    if (data.vehicleMileage) {
        data.vehicleMileage = timestampedValueSchemaResponseTransformer(data.vehicleMileage);
    }
    if (data.brakeFluidLow) {
        data.brakeFluidLow = timestampedValueSchemaResponseTransformer(data.brakeFluidLow);
    }
    if (data.gearStatus) {
        data.gearStatus = timestampedValueSchemaResponseTransformer(data.gearStatus);
    }
    if (data.tirePressureStatusFrontLeft) {
        data.tirePressureStatusFrontLeft = timestampedValueSchemaResponseTransformer(data.tirePressureStatusFrontLeft);
    }
    if (data.tirePressureStatusValidFrontLeft) {
        data.tirePressureStatusValidFrontLeft = timestampedValueSchemaResponseTransformer(data.tirePressureStatusValidFrontLeft);
    }
    if (data.tirePressureStatusFrontRight) {
        data.tirePressureStatusFrontRight = timestampedValueSchemaResponseTransformer(data.tirePressureStatusFrontRight);
    }
    if (data.tirePressureStatusValidFrontRight) {
        data.tirePressureStatusValidFrontRight = timestampedValueSchemaResponseTransformer(data.tirePressureStatusValidFrontRight);
    }
    if (data.tirePressureStatusRearLeft) {
        data.tirePressureStatusRearLeft = timestampedValueSchemaResponseTransformer(data.tirePressureStatusRearLeft);
    }
    if (data.tirePressureStatusValidRearLeft) {
        data.tirePressureStatusValidRearLeft = timestampedValueSchemaResponseTransformer(data.tirePressureStatusValidRearLeft);
    }
    if (data.tirePressureStatusRearRight) {
        data.tirePressureStatusRearRight = timestampedValueSchemaResponseTransformer(data.tirePressureStatusRearRight);
    }
    if (data.tirePressureStatusValidRearRight) {
        data.tirePressureStatusValidRearRight = timestampedValueSchemaResponseTransformer(data.tirePressureStatusValidRearRight);
    }
    if (data.batteryLevel) {
        data.batteryLevel = timestampedValueSchemaResponseTransformer(data.batteryLevel);
    }
    if (data.chargerState) {
        data.chargerState = timestampedValueSchemaResponseTransformer(data.chargerState);
    }
    if (data.batteryLimit) {
        data.batteryLimit = timestampedValueSchemaResponseTransformer(data.batteryLimit);
    }
    if (data.remoteChargingAvailable) {
        data.remoteChargingAvailable = timestampedValueSchemaResponseTransformer(data.remoteChargingAvailable);
    }
    if (data.batteryHvThermalEvent) {
        data.batteryHvThermalEvent = timestampedValueSchemaResponseTransformer(data.batteryHvThermalEvent);
    }
    if (data.rangeThreshold) {
        data.rangeThreshold = timestampedValueSchemaResponseTransformer(data.rangeThreshold);
    }
    if (data.distanceToEmpty) {
        data.distanceToEmpty = timestampedValueSchemaResponseTransformer(data.distanceToEmpty);
    }
    if (data.otaAvailableVersion) {
        data.otaAvailableVersion = timestampedValueSchemaResponseTransformer(data.otaAvailableVersion);
    }
    if (data.otaAvailableVersionGitHash) {
        data.otaAvailableVersionGitHash = timestampedValueSchemaResponseTransformer(data.otaAvailableVersionGitHash);
    }
    if (data.otaAvailableVersionNumber) {
        data.otaAvailableVersionNumber = timestampedValueSchemaResponseTransformer(data.otaAvailableVersionNumber);
    }
    if (data.otaAvailableVersionWeek) {
        data.otaAvailableVersionWeek = timestampedValueSchemaResponseTransformer(data.otaAvailableVersionWeek);
    }
    if (data.otaAvailableVersionYear) {
        data.otaAvailableVersionYear = timestampedValueSchemaResponseTransformer(data.otaAvailableVersionYear);
    }
    if (data.otaCurrentVersion) {
        data.otaCurrentVersion = timestampedValueSchemaResponseTransformer(data.otaCurrentVersion);
    }
    if (data.otaCurrentVersionGitHash) {
        data.otaCurrentVersionGitHash = timestampedValueSchemaResponseTransformer(data.otaCurrentVersionGitHash);
    }
    if (data.otaCurrentVersionNumber) {
        data.otaCurrentVersionNumber = timestampedValueSchemaResponseTransformer(data.otaCurrentVersionNumber);
    }
    if (data.otaCurrentVersionWeek) {
        data.otaCurrentVersionWeek = timestampedValueSchemaResponseTransformer(data.otaCurrentVersionWeek);
    }
    if (data.otaCurrentVersionYear) {
        data.otaCurrentVersionYear = timestampedValueSchemaResponseTransformer(data.otaCurrentVersionYear);
    }
    if (data.otaDownloadProgress) {
        data.otaDownloadProgress = timestampedValueSchemaResponseTransformer(data.otaDownloadProgress);
    }
    if (data.otaInstallDuration) {
        data.otaInstallDuration = timestampedValueSchemaResponseTransformer(data.otaInstallDuration);
    }
    if (data.otaInstallProgress) {
        data.otaInstallProgress = timestampedValueSchemaResponseTransformer(data.otaInstallProgress);
    }
    if (data.otaInstallReady) {
        data.otaInstallReady = timestampedValueSchemaResponseTransformer(data.otaInstallReady);
    }
    if (data.otaInstallTime) {
        data.otaInstallTime = timestampedValueSchemaResponseTransformer(data.otaInstallTime);
    }
    if (data.otaInstallType) {
        data.otaInstallType = timestampedValueSchemaResponseTransformer(data.otaInstallType);
    }
    if (data.otaStatus) {
        data.otaStatus = timestampedValueSchemaResponseTransformer(data.otaStatus);
    }
    if (data.otaCurrentStatus) {
        data.otaCurrentStatus = timestampedValueSchemaResponseTransformer(data.otaCurrentStatus);
    }
    if (data.cabinClimateInteriorTemperature) {
        data.cabinClimateInteriorTemperature = timestampedValueSchemaResponseTransformer(data.cabinClimateInteriorTemperature);
    }
    if (data.cabinPreconditioningStatus) {
        data.cabinPreconditioningStatus = timestampedValueSchemaResponseTransformer(data.cabinPreconditioningStatus);
    }
    if (data.cabinPreconditioningType) {
        data.cabinPreconditioningType = timestampedValueSchemaResponseTransformer(data.cabinPreconditioningType);
    }
    if (data.petModeStatus) {
        data.petModeStatus = timestampedValueSchemaResponseTransformer(data.petModeStatus);
    }
    if (data.petModeTemperatureStatus) {
        data.petModeTemperatureStatus = timestampedValueSchemaResponseTransformer(data.petModeTemperatureStatus);
    }
    if (data.cabinClimateDriverTemperature) {
        data.cabinClimateDriverTemperature = timestampedValueSchemaResponseTransformer(data.cabinClimateDriverTemperature);
    }
    if (data.gearGuardVideoStatus) {
        data.gearGuardVideoStatus = timestampedValueSchemaResponseTransformer(data.gearGuardVideoStatus);
    }
    if (data.gearGuardVideoMode) {
        data.gearGuardVideoMode = timestampedValueSchemaResponseTransformer(data.gearGuardVideoMode);
    }
    if (data.gearGuardVideoTermsAccepted) {
        data.gearGuardVideoTermsAccepted = timestampedValueSchemaResponseTransformer(data.gearGuardVideoTermsAccepted);
    }
    if (data.defrostDefogStatus) {
        data.defrostDefogStatus = timestampedValueSchemaResponseTransformer(data.defrostDefogStatus);
    }
    if (data.steeringWheelHeat) {
        data.steeringWheelHeat = timestampedValueSchemaResponseTransformer(data.steeringWheelHeat);
    }
    if (data.seatFrontLeftHeat) {
        data.seatFrontLeftHeat = timestampedValueSchemaResponseTransformer(data.seatFrontLeftHeat);
    }
    if (data.seatFrontRightHeat) {
        data.seatFrontRightHeat = timestampedValueSchemaResponseTransformer(data.seatFrontRightHeat);
    }
    if (data.seatRearLeftHeat) {
        data.seatRearLeftHeat = timestampedValueSchemaResponseTransformer(data.seatRearLeftHeat);
    }
    if (data.seatRearRightHeat) {
        data.seatRearRightHeat = timestampedValueSchemaResponseTransformer(data.seatRearRightHeat);
    }
    if (data.chargerStatus) {
        data.chargerStatus = timestampedValueSchemaResponseTransformer(data.chargerStatus);
    }
    if (data.seatFrontLeftVent) {
        data.seatFrontLeftVent = timestampedValueSchemaResponseTransformer(data.seatFrontLeftVent);
    }
    if (data.seatFrontRightVent) {
        data.seatFrontRightVent = timestampedValueSchemaResponseTransformer(data.seatFrontRightVent);
    }
    if (data.chargerDerateStatus) {
        data.chargerDerateStatus = timestampedValueSchemaResponseTransformer(data.chargerDerateStatus);
    }
    if (data.driveMode) {
        data.driveMode = timestampedValueSchemaResponseTransformer(data.driveMode);
    }
    if (data.serviceMode) {
        data.serviceMode = timestampedValueSchemaResponseTransformer(data.serviceMode);
    }
    if (data.trailerStatus) {
        data.trailerStatus = timestampedValueSchemaResponseTransformer(data.trailerStatus);
    }
    if (data.carWashMode) {
        data.carWashMode = timestampedValueSchemaResponseTransformer(data.carWashMode);
    }
    if (data.chargePortState) {
        data.chargePortState = timestampedValueSchemaResponseTransformer(data.chargePortState);
    }
    if (data.windowsNextAction) {
        data.windowsNextAction = timestampedValueSchemaResponseTransformer(data.windowsNextAction);
    }
    if (data.btmFfHardwareFailureStatus) {
        data.btmFfHardwareFailureStatus = timestampedValueSchemaResponseTransformer(data.btmFfHardwareFailureStatus);
    }
    if (data.btmIcHardwareFailureStatus) {
        data.btmIcHardwareFailureStatus = timestampedValueSchemaResponseTransformer(data.btmIcHardwareFailureStatus);
    }
    if (data.btmLfdHardwareFailureStatus) {
        data.btmLfdHardwareFailureStatus = timestampedValueSchemaResponseTransformer(data.btmLfdHardwareFailureStatus);
    }
    if (data.btmRfHardwareFailureStatus) {
        data.btmRfHardwareFailureStatus = timestampedValueSchemaResponseTransformer(data.btmRfHardwareFailureStatus);
    }
    if (data.btmRfdHardwareFailureStatus) {
        data.btmRfdHardwareFailureStatus = timestampedValueSchemaResponseTransformer(data.btmRfdHardwareFailureStatus);
    }
    if (data.chargingTimeEstimationValidity) {
        data.chargingTimeEstimationValidity = timestampedValueSchemaResponseTransformer(data.chargingTimeEstimationValidity);
    }
    if (data.limitedAccelCold) {
        data.limitedAccelCold = timestampedValueSchemaResponseTransformer(data.limitedAccelCold);
    }
    if (data.limitedRegenCold) {
        data.limitedRegenCold = timestampedValueSchemaResponseTransformer(data.limitedRegenCold);
    }
    if (data.rearHitchStatus) {
        data.rearHitchStatus = timestampedValueSchemaResponseTransformer(data.rearHitchStatus);
    }
    if (data.tirePressureFrontLeft) {
        data.tirePressureFrontLeft = timestampedValueSchemaResponseTransformer(data.tirePressureFrontLeft);
    }
    if (data.tirePressureFrontRight) {
        data.tirePressureFrontRight = timestampedValueSchemaResponseTransformer(data.tirePressureFrontRight);
    }
    if (data.tirePressureRearLeft) {
        data.tirePressureRearLeft = timestampedValueSchemaResponseTransformer(data.tirePressureRearLeft);
    }
    if (data.tirePressureRearRight) {
        data.tirePressureRearRight = timestampedValueSchemaResponseTransformer(data.tirePressureRearRight);
    }
    if (data.batteryCapacity) {
        data.batteryCapacity = timestampedValueSchemaResponseTransformer(data.batteryCapacity);
    }
    return data;
};

const vehicleDetailsSchemaResponseTransformer = (data: any) => {
    if (data.vehicleState) {
        data.vehicleState = vehicleStateSchemaResponseTransformer(data.vehicleState);
    }
    return data;
};

const userVehicleSchemaResponseTransformer = (data: any) => {
    if (data.vehicle) {
        data.vehicle = vehicleDetailsSchemaResponseTransformer(data.vehicle);
    }
    return data;
};

const userInfoSchemaResponseTransformer = (data: any) => {
    if (data.vehicles) {
        data.vehicles = data.vehicles.map((item: any) => userVehicleSchemaResponseTransformer(item));
    }
    return data;
};

export const getUserInfoResponseTransformer = async (data: any): Promise<GetUserInfoResponse> => {
    if (data.data) {
        if (data.data.currentUser) {
            data.data.currentUser = userInfoSchemaResponseTransformer(data.data.currentUser);
        }
    }
    return data;
};

export const currentUserForLoginResponseTransformer = async (data: any): Promise<CurrentUserForLoginResponse> => {
    if (data.data) {
        if (data.data.currentUser) {
            data.data.currentUser = userInfoSchemaResponseTransformer(data.data.currentUser);
        }
    }
    return data;
};

const deliverySchemaResponseTransformer = (data: any) => {
    if (data.appointmentDetails) {
        if (data.appointmentDetails.startDateTime) {
            data.appointmentDetails.startDateTime = new Date(data.appointmentDetails.startDateTime);
        }
        if (data.appointmentDetails.endDateTime) {
            data.appointmentDetails.endDateTime = new Date(data.appointmentDetails.endDateTime);
        }
    }
    return data;
};

export const deliveryResponseTransformer = async (data: any): Promise<DeliveryResponse> => {
    if (data.data) {
        if (data.data.delivery) {
            data.data.delivery = deliverySchemaResponseTransformer(data.data.delivery);
        }
    }
    return data;
};

const chargingSessionSummarySchemaResponseTransformer = (data: any) => {
    if (data.startInstant) {
        data.startInstant = new Date(data.startInstant);
    }
    if (data.endInstant) {
        data.endInstant = new Date(data.endInstant);
    }
    return data;
};

export const getCompletedSessionSummariesResponseTransformer = async (data: any): Promise<GetCompletedSessionSummariesResponse> => {
    if (data.data) {
        if (data.data.getCompletedSessionSummaries) {
            data.data.getCompletedSessionSummaries = data.data.getCompletedSessionSummaries.map((item: any) => chargingSessionSummarySchemaResponseTransformer(item));
        }
    }
    return data;
};

const liveSessionDataSchemaResponseTransformer = (data: any) => {
    if (data.vehicleChargerState) {
        data.vehicleChargerState = timestampedValueSchemaResponseTransformer(data.vehicleChargerState);
    }
    if (data.startTime) {
        data.startTime = new Date(data.startTime);
    }
    if (data.timeRemaining) {
        data.timeRemaining = timestampedValueSchemaResponseTransformer(data.timeRemaining);
    }
    if (data.kilometersChargedPerHour) {
        data.kilometersChargedPerHour = timestampedValueSchemaResponseTransformer(data.kilometersChargedPerHour);
    }
    if (data.power) {
        data.power = timestampedValueSchemaResponseTransformer(data.power);
    }
    if (data.rangeAddedThisSession) {
        data.rangeAddedThisSession = timestampedValueSchemaResponseTransformer(data.rangeAddedThisSession);
    }
    if (data.totalChargedEnergy) {
        data.totalChargedEnergy = timestampedValueSchemaResponseTransformer(data.totalChargedEnergy);
    }
    return data;
};

export const getLiveSessionDataResponseTransformer = async (data: any): Promise<GetLiveSessionDataResponse> => {
    if (data.data) {
        if (data.data.getLiveSessionData) {
            data.data.getLiveSessionData = liveSessionDataSchemaResponseTransformer(data.data.getLiveSessionData);
        }
    }
    return data;
};

export const getLiveSessionHistoryResponseTransformer = async (data: any): Promise<GetLiveSessionHistoryResponse> => {
    if (data.data) {
        if (data.data.getLiveSessionHistory) {
            if (data.data.getLiveSessionHistory.chartData) {
                data.data.getLiveSessionHistory.chartData = data.data.getLiveSessionHistory.chartData.map((item: any) => {
                    if (item.time) {
                        item.time = new Date(item.time);
                    }
                    return item;
                });
            }
        }
    }
    return data;
};

export const getNonRivianUserSessionResponseTransformer = async (data: any): Promise<GetNonRivianUserSessionResponse> => {
    if (data.data) {
        if (data.data.getNonRivianUserSession) {
            if (data.data.getNonRivianUserSession.vehicleChargerState) {
                if (data.data.getNonRivianUserSession.vehicleChargerState.updatedAt) {
                    data.data.getNonRivianUserSession.vehicleChargerState.updatedAt = new Date(data.data.getNonRivianUserSession.vehicleChargerState.updatedAt);
                }
            }
        }
    }
    return data;
};

export const getVehicleStateResponseTransformer = async (data: any): Promise<GetVehicleStateResponse> => {
    if (data.data) {
        if (data.data.vehicleState) {
            data.data.vehicleState = vehicleStateSchemaResponseTransformer(data.data.vehicleState);
        }
    }
    return data;
};

export const getVehicleLastConnectionResponseTransformer = async (data: any): Promise<GetVehicleLastConnectionResponse> => {
    if (data.data) {
        if (data.data.vehicleState) {
            if (data.data.vehicleState.cloudConnection) {
                if (data.data.vehicleState.cloudConnection.lastSync) {
                    data.data.vehicleState.cloudConnection.lastSync = new Date(data.data.vehicleState.cloudConnection.lastSync);
                }
            }
        }
    }
    return data;
};
