// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://rivian.com/api/gql' | 'https://media.rivian.com' | 'wss://api.rivian.com' | 'https://rivian.com' | 'wss://api.rivian.com' | 'https://media.rivian.com' | (string & {});
};

export type GraphQlRequest = {
    operationName: string;
    variables?: {
        [key: string]: unknown;
    };
    query: string;
};

export type GraphQlResponse = {
    data?: {
        [key: string]: unknown;
    };
    errors?: Array<{
        message?: string;
    }>;
};

export type CreateCsrfTokenResponse = {
    data?: {
        createCsrfToken?: {
            __typename?: string;
            csrfToken?: string;
            appSessionToken?: string;
        };
    };
};

export type LoginResponse = {
    data?: {
        loginWithOTP?: {
            __typename?: string;
            accessToken?: string;
            refreshToken?: string;
            userSessionToken?: string;
        };
    };
};

export type MfaLoginResponse = {
    data?: {
        login?: {
            __typename?: string;
            otpToken?: string;
        };
    };
};

export type UserInfo = {
    __typename?: string;
    id?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    address?: UserAddress;
    vehicles?: Array<UserVehicle>;
    enrolledPhones?: Array<EnrolledPhone>;
    pendingInvites?: Array<PendingInvite>;
};

export type UserAddress = {
    __typename?: string;
    id?: string;
    types?: Array<'PRIMARY' | 'SHIPPING'>;
    line1?: string;
    line2?: string | null;
    city?: string;
    state?: string;
    postalCode?: string;
    country?: string;
};

export type UserVehicle = {
    __typename?: string;
    id?: string;
    name?: string | null;
    owner?: string | null;
    roles?: Array<string>;
    vin?: string;
    vas?: {
        vasVehicleId?: string;
        vehiclePublicKey?: string;
    };
    vehicle?: VehicleDetails;
    settings?: {
        name?: {
            value?: string | null;
        };
    };
};

export type VehicleDetails = {
    __typename?: string;
    model?: 'R1T' | 'R1S';
    modelYear?: number;
    mobileConfiguration?: MobileConfiguration;
    deviceSlots?: {
        phone?: {
            max?: number;
            free?: number;
        };
    };
    cccCapable?: boolean;
    cccReady?: boolean;
    cccEnabled?: boolean;
    legacyEnabled?: boolean;
    otaEarlyAccessStatus?: boolean;
    vehicleState?: VehicleState;
    maintenanceSchedule?: MaintenanceSchedule;
};

export type MobileConfiguration = {
    __typename?: string;
    trimOption?: ConfigOption;
    exteriorColorOption?: ConfigOption;
    interiorColorOption?: ConfigOption;
    driveSystemOption?: ConfigOption;
    tonneauOption?: ConfigOption | null;
    wheelOption?: ConfigOption;
    driveSystemDriveModes?: Array<string>;
    driveSystemTowingDriveModes?: Array<string>;
    maxVehiclePower?: number;
    chargePort?: 'CCS' | 'J1772';
};

export type ConfigOption = {
    __typename?: string;
    optionId?: string;
    optionName?: string;
};

export type MaintenanceSchedule = {
    sections?: Array<{
        items?: Array<{
            description?: string;
            isDue?: boolean | null;
        }>;
        serviceLifetime?: {
            __typename?: string;
            km?: number;
            mi?: number;
        } | {
            __typename?: string;
            year?: number;
        };
    }>;
};

export type EnrolledPhone = {
    vas?: {
        vasPhoneId?: string;
        publicKey?: string;
    };
    enrolled?: Array<{
        deviceType?: string;
        deviceName?: string;
        vehicleId?: string;
        identityId?: string;
        shortName?: string;
    }>;
};

export type PendingInvite = {
    id?: string;
    invitedByFirstName?: string;
    role?: string;
    status?: string;
    vehicleId?: string;
    vehicleModel?: string;
    email?: string;
};

export type VehicleState = {
    __typename?: string;
    gnssLocation?: {
        latitude?: number;
        longitude?: number;
        timeStamp?: Date;
        isAuthorized?: boolean;
    } | null;
    gnssSpeed?: TimestampedValue;
    gnssAltitude?: TimestampedValue;
    gnssError?: {
        timeStamp?: Date;
        positionVertical?: number;
        positionHorizontal?: number;
        speed?: number;
        bearing?: number;
    } | null;
    alarmSoundStatus?: TimestampedValue;
    timeToEndOfCharge?: TimestampedValue;
    doorFrontLeftLocked?: TimestampedValue;
    doorFrontLeftClosed?: TimestampedValue;
    doorFrontRightLocked?: TimestampedValue;
    doorFrontRightClosed?: TimestampedValue;
    doorRearLeftLocked?: TimestampedValue;
    doorRearLeftClosed?: TimestampedValue;
    doorRearRightLocked?: TimestampedValue;
    doorRearRightClosed?: TimestampedValue;
    windowFrontLeftClosed?: TimestampedValue;
    windowFrontRightClosed?: TimestampedValue;
    windowFrontLeftCalibrated?: TimestampedValue;
    windowFrontRightCalibrated?: TimestampedValue;
    windowRearLeftCalibrated?: TimestampedValue;
    windowRearRightCalibrated?: TimestampedValue;
    windowRearLeftClosed?: TimestampedValue;
    windowRearRightClosed?: TimestampedValue;
    closureFrunkLocked?: TimestampedValue;
    closureFrunkClosed?: TimestampedValue;
    closureFrunkNextAction?: TimestampedValue;
    closureLiftgateLocked?: TimestampedValue;
    closureLiftgateClosed?: TimestampedValue;
    closureLiftgateNextAction?: TimestampedValue;
    closureSideBinLeftLocked?: TimestampedValue;
    closureSideBinLeftClosed?: TimestampedValue;
    closureSideBinRightLocked?: TimestampedValue;
    closureSideBinLeftNextAction?: TimestampedValue;
    closureSideBinRightClosed?: TimestampedValue;
    closureSideBinRightNextAction?: TimestampedValue;
    closureTailgateLocked?: TimestampedValue;
    closureTailgateClosed?: TimestampedValue;
    closureTailgateNextAction?: TimestampedValue;
    closureTonneauLocked?: TimestampedValue;
    closureTonneauClosed?: TimestampedValue;
    gearGuardLocked?: TimestampedValue;
    wiperFluidState?: TimestampedValue;
    powerState?: TimestampedValue;
    batteryHvThermalEventPropagation?: TimestampedValue;
    twelveVoltBatteryHealth?: TimestampedValue;
    vehicleMileage?: TimestampedValue;
    brakeFluidLow?: TimestampedValue;
    gearStatus?: TimestampedValue;
    tirePressureStatusFrontLeft?: TimestampedValue;
    tirePressureStatusValidFrontLeft?: TimestampedValue;
    tirePressureStatusFrontRight?: TimestampedValue;
    tirePressureStatusValidFrontRight?: TimestampedValue;
    tirePressureStatusRearLeft?: TimestampedValue;
    tirePressureStatusValidRearLeft?: TimestampedValue;
    tirePressureStatusRearRight?: TimestampedValue;
    tirePressureStatusValidRearRight?: TimestampedValue;
    batteryLevel?: TimestampedValue;
    chargerState?: TimestampedValue;
    batteryLimit?: TimestampedValue;
    remoteChargingAvailable?: TimestampedValue;
    batteryHvThermalEvent?: TimestampedValue;
    rangeThreshold?: TimestampedValue;
    distanceToEmpty?: TimestampedValue;
    otaAvailableVersion?: TimestampedValue;
    otaAvailableVersionGitHash?: TimestampedValue;
    otaAvailableVersionNumber?: TimestampedValue;
    otaAvailableVersionWeek?: TimestampedValue;
    otaAvailableVersionYear?: TimestampedValue;
    otaCurrentVersion?: TimestampedValue;
    otaCurrentVersionGitHash?: TimestampedValue;
    otaCurrentVersionNumber?: TimestampedValue;
    otaCurrentVersionWeek?: TimestampedValue;
    otaCurrentVersionYear?: TimestampedValue;
    otaDownloadProgress?: TimestampedValue;
    otaInstallDuration?: TimestampedValue;
    otaInstallProgress?: TimestampedValue;
    otaInstallReady?: TimestampedValue;
    otaInstallTime?: TimestampedValue;
    otaInstallType?: TimestampedValue;
    otaStatus?: TimestampedValue;
    otaCurrentStatus?: TimestampedValue;
    cabinClimateInteriorTemperature?: TimestampedValue;
    cabinPreconditioningStatus?: TimestampedValue;
    cabinPreconditioningType?: TimestampedValue;
    petModeStatus?: TimestampedValue;
    petModeTemperatureStatus?: TimestampedValue;
    cabinClimateDriverTemperature?: TimestampedValue;
    gearGuardVideoStatus?: TimestampedValue;
    gearGuardVideoMode?: TimestampedValue;
    gearGuardVideoTermsAccepted?: TimestampedValue;
    defrostDefogStatus?: TimestampedValue;
    steeringWheelHeat?: TimestampedValue;
    seatFrontLeftHeat?: TimestampedValue;
    seatFrontRightHeat?: TimestampedValue;
    seatRearLeftHeat?: TimestampedValue;
    seatRearRightHeat?: TimestampedValue;
    chargerStatus?: TimestampedValue;
    seatFrontLeftVent?: TimestampedValue;
    seatFrontRightVent?: TimestampedValue;
    chargerDerateStatus?: TimestampedValue;
    driveMode?: TimestampedValue;
    serviceMode?: TimestampedValue;
    trailerStatus?: TimestampedValue;
    carWashMode?: TimestampedValue;
    chargePortState?: TimestampedValue;
    windowsNextAction?: TimestampedValue;
    btmFfHardwareFailureStatus?: TimestampedValue;
    btmIcHardwareFailureStatus?: TimestampedValue;
    btmLfdHardwareFailureStatus?: TimestampedValue;
    btmRfHardwareFailureStatus?: TimestampedValue;
    btmRfdHardwareFailureStatus?: TimestampedValue;
    chargingTimeEstimationValidity?: TimestampedValue;
    limitedAccelCold?: TimestampedValue;
    limitedRegenCold?: TimestampedValue;
    rearHitchStatus?: TimestampedValue;
    tirePressureFrontLeft?: TimestampedValue;
    tirePressureFrontRight?: TimestampedValue;
    tirePressureRearLeft?: TimestampedValue;
    tirePressureRearRight?: TimestampedValue;
    batteryCapacity?: TimestampedValue;
    supportedFeatures?: Array<SupportedFeature>;
};

export type TimestampedValue = {
    timeStamp?: Date;
    value?: string | number | boolean | number;
} | null;

export type SupportedFeature = {
    name?: string;
    status?: 'AVAILABLE' | 'UNAVAILABLE';
};

export type TrailerProfile = {
    __typename?: string;
    rangeStatus?: string;
    weight?: number;
    onRoadEfficiency?: number;
    offRoadEfficiency?: number;
    name?: string;
} | null;

export type TransactionStep = {
    sourceStatus?: {
        status?: string;
        details?: {
            [key: string]: unknown;
        } | null;
    };
    consumerStatus?: {
        displayOrder?: number;
        current?: boolean;
        complete?: boolean;
        locked?: boolean;
        inProgress?: boolean;
        notStarted?: boolean;
        error?: boolean;
    };
};

export type VehicleCommand = 'WAKE_VEHICLE' | 'OPEN_FRUNK' | 'CLOSE_FRUNK' | 'OPEN_ALL_WINDOWS' | 'CLOSE_ALL_WINDOWS' | 'UNLOCK_ALL_CLOSURES' | 'LOCK_ALL_CLOSURES' | 'ENABLE_GEAR_GUARD_VIDEO' | 'DISABLE_GEAR_GUARD_VIDEO' | 'HONK_AND_FLASH_LIGHTS' | 'OPEN_TONNEAU_COVER' | 'CLOSE_TONNEAU_COVER';

export type WallboxRecord = {
    __typename?: string;
    wallboxId?: string;
    userId?: string;
    wifiId?: string;
    name?: string;
    linked?: boolean;
    latitude?: number;
    longitude?: number;
    chargingStatus?: 'AVAILABLE' | 'CHARGING' | 'DISCONNECTED';
    power?: number | null;
    currentVoltage?: number | null;
    currentAmps?: number | null;
    softwareVersion?: string;
    model?: string;
    serialNumber?: string;
    maxPower?: string;
    maxVoltage?: string;
    maxAmps?: string | null;
};

export type ChargingSessionSummary = {
    chargerType?: string;
    currencyCode?: string | null;
    paidTotal?: number | null;
    startInstant?: Date;
    endInstant?: Date;
    totalEnergyKwh?: number;
    rangeAddedKm?: number | null;
    city?: string;
    transactionId?: string;
    vehicleId?: string | null;
    vehicleName?: string | null;
    vendor?: string;
    isRoamingNetwork?: boolean;
    isPublic?: boolean;
    isHomeCharger?: boolean;
    meta?: {
        transactionIdGroupingKey?: string;
        dataSources?: Array<string>;
    };
};

export type LiveSessionData = {
    isRivianCharger?: boolean;
    isFreeSession?: boolean;
    vehicleChargerState?: TimestampedValue;
    chargerId?: string;
    startTime?: Date;
    timeElapsed?: string;
    timeRemaining?: TimestampedValue;
    kilometersChargedPerHour?: TimestampedValue;
    power?: TimestampedValue;
    rangeAddedThisSession?: TimestampedValue;
    totalChargedEnergy?: TimestampedValue;
    currentPrice?: number;
};

export type ChargingSchedule = {
    /**
     * Minutes after midnight to start charging
     */
    startTime?: number;
    /**
     * Duration in minutes
     */
    duration?: number;
    location?: {
        latitude?: number;
        longitude?: number;
    };
    amperage?: number;
    enabled?: boolean;
    weekDays?: Array<'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'>;
};

export type ChargerDetails = {
    id?: string;
    name?: string;
    location?: {
        addressComponents?: Array<{
            type?: string;
            shortName?: string;
            longName?: string;
        }>;
        formattedAddress?: string;
        coordinate?: {
            latitude?: number;
            longitude?: number;
        };
        navCoordinate?: {
            latitude?: number;
            longitude?: number;
        };
    };
    distance?: number;
    driveDetails?: {
        driveDistance?: number;
        driveDuration?: number;
        detourDistance?: number;
        detourDuration?: number;
    } | null;
    chargingStation?: {
        network?: string;
        networkId?: string;
        maxKw?: number;
        note?: string;
        chargers?: Array<{
            locationId?: string;
            pluginDependency?: string;
            connectors?: Array<{
                id?: string;
                evseId?: string;
                evseUid?: string;
                name?: string;
                level?: string;
                maxKw?: number;
                chargingPrice?: {
                    level?: string | null;
                    description?: string | null;
                    amount?: number | null;
                    currency?: string | null;
                    lastUpdateTime?: string | null;
                    symbol?: string | null;
                    type?: string | null;
                    unit?: string | null;
                } | null;
                type?: 'CCS' | 'J1772';
                free?: boolean;
                vend?: string | null;
                state?: string;
            }>;
        }>;
        operatingHours?: {
            alwaysOpen?: boolean;
            hours?: Array<{
                close?: number;
                day?: string;
                open?: number;
            }>;
        };
    };
    adapterRequired?: boolean;
};

export type Delivery = {
    __typename?: string;
    status?: string;
    carrier?: string;
    deliveryAddress?: {
        addressLine1?: string;
        addressLine2?: string | null;
        city?: string;
        state?: string;
        country?: string;
        zipcode?: string;
    };
    appointmentDetails?: {
        appointmentId?: string;
        startDateTime?: Date;
        endDateTime?: Date;
        timeZone?: string;
    };
    vehicleVIN?: string;
};

export type OrderSnapshot = {
    id?: string;
    type?: 'PRE_ORDER' | 'VEHICLE' | 'RETAIL';
    orderDate?: string;
    state?: string;
    configurationStatus?: string | null;
    fulfillmentSummaryStatus?: string | null;
    total?: number;
    paidTotal?: number;
    subtotal?: number;
    currency?: string;
    consumerStatuses?: {
        isConsumerFlowComplete?: boolean;
    } | null;
    items?: Array<{
        id?: string;
        title?: string;
        type?: string;
        sku?: string;
    }>;
};

export type TripPlanResult = {
    routes?: Array<{
        routeResponse?: {
            [key: string]: unknown;
        };
        destinationReached?: boolean;
        totalChargingDuration?: number;
        arrivalSOC?: number;
        arrivalReachableDistance?: number;
        energyConsumptionOnLeg?: number | null;
        batteryEmptyToDestinationDistance?: number | null;
        batteryEmptyLocationLatitude?: number | null;
        batteryEmptyLocationLongitude?: number | null;
        waypoints?: Array<{
            waypointType?: 'DC_CHARGE_STATION' | 'OTHER';
            entityId?: string;
            name?: string | null;
            latitude?: number;
            longitude?: number;
            maxPower?: number | null;
            chargeDuration?: number;
            arrivalSOC?: number;
            arrivalReachableDistance?: number;
            departureSOC?: number;
            departureReachableDistance?: number;
            adapterRequired?: boolean | null;
        }>;
    }>;
    tripPlanStatus?: string;
    chargeStationsAvailable?: boolean;
    socBelowLimit?: boolean;
};

export type PlaceResult = {
    id?: string;
    name?: string;
    distance?: number;
    location?: {
        addressComponents?: Array<{
            type?: string;
            shortName?: string;
            longName?: string;
        }>;
        coordinate?: {
            latitude?: number;
            longitude?: number;
        };
        navCoordinate?: {
            latitude?: number;
            longitude?: number;
        };
        formattedAddress?: string;
    };
    driveDetails?: {
        driveDistance?: number;
        driveDuration?: number;
        detourDistance?: number;
        detourDuration?: number;
    };
};

export type VehicleMobileImage = {
    __typename?: string;
    vehicleId?: string;
    orderId?: string;
    url?: string;
    resolution?: string;
    size?: 'small' | 'large';
    design?: 'dark' | 'light';
    placement?: 'front' | 'rear' | 'side' | 'side-charging' | 'overhead';
    overlays?: Array<{
        url?: string;
        overlay?: string;
        zIndex?: number;
    }> | null;
};

export type CreateCsrfTokenData = {
    body: {
        operationName?: string;
        variables?: Array<unknown>;
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#CreateCSRFToken';
};

export type CreateCsrfTokenResponses = {
    /**
     * CSRF token created
     */
    200: CreateCsrfTokenResponse;
};

export type CreateCsrfTokenResponse2 = CreateCsrfTokenResponses[keyof CreateCsrfTokenResponses];

export type LoginData = {
    body: {
        operationName?: string;
        variables?: {
            email?: string;
            password?: string;
        };
        query?: string;
    };
    headers: {
        'a-sess': string;
        'csrf-token': string;
        'apollographql-client-name': string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#Login';
};

export type LoginResponses = {
    /**
     * Login successful or MFA required
     */
    200: LoginResponse | MfaLoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LoginWithOtpData = {
    body: {
        operationName?: string;
        variables?: {
            email?: string;
            otpCode?: string;
            otpToken?: string;
        };
        query?: string;
    };
    headers: {
        'a-sess': string;
        'csrf-token': string;
        'apollographql-client-name': string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#LoginWithOTP';
};

export type LoginWithOtpResponses = {
    /**
     * MFA login successful
     */
    200: LoginResponse;
};

export type LoginWithOtpResponse = LoginWithOtpResponses[keyof LoginWithOtpResponses];

export type GetUserInfoData = {
    body: {
        operationName?: string;
        variables?: {
            [key: string]: unknown;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#getUserInfo';
};

export type GetUserInfoResponses = {
    /**
     * User info retrieved
     */
    200: {
        data?: {
            currentUser?: UserInfo;
        };
    };
};

export type GetUserInfoResponse = GetUserInfoResponses[keyof GetUserInfoResponses];

export type CurrentUserForLoginData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/gateway/graphql#CurrentUserForLogin';
};

export type CurrentUserForLoginResponses = {
    /**
     * Current user details
     */
    200: {
        data?: {
            currentUser?: UserInfo;
        };
    };
};

export type CurrentUserForLoginResponse = CurrentUserForLoginResponses[keyof CurrentUserForLoginResponses];

export type VehicleOrdersData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/gateway/graphql#vehicleOrders';
};

export type VehicleOrdersResponses = {
    /**
     * Vehicle orders list
     */
    200: {
        data?: {
            orders?: {
                data?: Array<OrderSnapshot>;
            };
        };
    };
};

export type VehicleOrdersResponse = VehicleOrdersResponses[keyof VehicleOrdersResponses];

export type DeliveryData = {
    body: {
        operationName?: string;
        variables?: {
            orderId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#delivery';
};

export type DeliveryResponses = {
    /**
     * Delivery info
     */
    200: {
        data?: {
            delivery?: Delivery;
        };
    };
};

export type DeliveryResponse = DeliveryResponses[keyof DeliveryResponses];

export type OrderData = {
    body: {
        operationName?: string;
        variables?: {
            orderId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/orders/graphql#order';
};

export type OrderResponses = {
    /**
     * Order details
     */
    200: {
        data?: {
            order?: {
                vin?: string | null;
                state?: string;
                billingAddress?: {
                    firstName?: string;
                    lastName?: string;
                    line1?: string;
                    line2?: string | null;
                    city?: string;
                    state?: string;
                    country?: string;
                    postalCode?: string;
                };
                shippingAddress?: {
                    firstName?: string;
                    lastName?: string;
                    line1?: string;
                    line2?: string | null;
                    city?: string;
                    state?: string;
                    country?: string;
                    postalCode?: string;
                };
                orderCancelDate?: string | null;
                orderEmail?: string;
                currency?: string;
                locale?: string;
                storeId?: string;
                type?: string;
                subtotal?: number;
                discountTotal?: number;
                taxTotal?: number;
                feesTotal?: number;
                paidTotal?: number;
                remainingTotal?: number;
                outstandingBalance?: number;
                costAfterCredits?: number;
                total?: number;
                payments?: Array<{
                    id?: string;
                    intent?: string;
                    date?: string;
                    method?: string;
                    amount?: number;
                    referenceNumber?: string | null;
                    status?: string;
                    card?: {
                        last4?: string;
                        expiryDate?: string;
                        brand?: string;
                    } | null;
                    bank?: {
                        bankName?: string;
                        country?: string;
                        last4?: string;
                    } | null;
                    transactionNotes?: string | null;
                }>;
                tradeIns?: Array<{
                    tradeInReferenceId?: string;
                    amount?: number;
                }>;
                vehicle?: {
                    vehicleId?: string;
                    vin?: string | null;
                    modelYear?: number;
                    model?: string;
                    make?: string;
                } | null;
                items?: Array<{
                    id?: string;
                    subtotal?: number;
                    quantity?: number;
                    title?: string;
                    productId?: string;
                    type?: string;
                    unitPrice?: number;
                    sku?: string;
                }>;
            };
        };
    };
};

export type OrderResponse = OrderResponses[keyof OrderResponses];

export type SearchOrdersData = {
    body: {
        operationName?: string;
        variables?: {
            orderTypes?: Array<string>;
            orderStates?: Array<string> | null;
            dateRange?: {
                [key: string]: unknown;
            } | null;
            pageInfo?: {
                from?: number;
                size?: number;
            };
            sortFields?: {
                orderDate?: 'ASC' | 'DESC';
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/orders/graphql#searchOrders';
};

export type SearchOrdersResponses = {
    /**
     * Search results
     */
    200: {
        data?: {
            searchOrders?: {
                total?: number;
                data?: Array<OrderSnapshot>;
            };
        };
    };
};

export type SearchOrdersResponse = SearchOrdersResponses[keyof SearchOrdersResponses];

export type UserData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/orders/graphql#user';
};

export type UserResponses = {
    /**
     * User info
     */
    200: {
        data?: {
            user?: {
                email?: {
                    email?: string;
                };
                phone?: {
                    formatted?: string;
                };
                firstName?: string;
                lastName?: string;
                addresses?: Array<{
                    id?: string;
                    type?: Array<string>;
                    line1?: string;
                    line2?: string | null;
                    city?: string;
                    state?: string;
                    country?: string;
                    postalCode?: string;
                }>;
                newsletterSubscription?: boolean;
                smsSubscription?: boolean;
                registrationChannels2FA?: {
                    [key: string]: unknown;
                };
                userId?: string;
                vehicles?: Array<{
                    [key: string]: unknown;
                }>;
                invites?: Array<{
                    [key: string]: unknown;
                }>;
                orderSnapshots?: Array<OrderSnapshot>;
            };
        };
    };
};

export type UserResponse = UserResponses[keyof UserResponses];

export type PaymentMethodsData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/orders/graphql#paymentMethods';
};

export type PaymentMethodsResponses = {
    /**
     * Payment methods
     */
    200: {
        data?: {
            paymentMethods?: Array<{
                id?: string;
                type?: string;
                default?: boolean;
                card?: {
                    lastFour?: string;
                    brand?: string;
                    expiration?: string;
                    postalCode?: string;
                };
            }>;
        };
    };
};

export type PaymentMethodsResponse = PaymentMethodsResponses[keyof PaymentMethodsResponses];

export type TransactionStatusData = {
    body: {
        operationName?: string;
        variables?: {
            orderId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/t2d/graphql#transactionStatus';
};

export type TransactionStatusResponses = {
    /**
     * Transaction statuses
     */
    200: {
        data?: {
            transactionStatus?: {
                titleAndReg?: TransactionStep;
                tradeIn?: TransactionStep;
                finance?: TransactionStep;
                delivery?: TransactionStep;
                insurance?: TransactionStep;
                documentUpload?: TransactionStep;
                contracts?: TransactionStep;
                payment?: TransactionStep;
            };
        };
    };
};

export type TransactionStatusResponse = TransactionStatusResponses[keyof TransactionStatusResponses];

export type FinanceSummaryData = {
    body: {
        operationName?: string;
        variables?: {
            orderId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/t2d/graphql#financeSummary';
};

export type FinanceSummaryResponses = {
    /**
     * Finance summary
     */
    200: {
        data?: {
            financeSummary?: {
                orderId?: string;
                status?: string;
                financeChoice?: {
                    financeChoice?: string;
                    institutionName?: string | null;
                    paymentMethod?: string;
                    trackingNumber?: string | null;
                    preApprovedAmount?: string;
                    loanOfficerName?: string | null;
                    loanOfficerContact?: string | null;
                    downPayment?: string;
                    rate?: number;
                    term?: number;
                    rateAndTermSkipped?: boolean;
                };
            };
        };
    };
};

export type FinanceSummaryResponse = FinanceSummaryResponses[keyof FinanceSummaryResponses];

export type GetProvisionedCampSpeakersData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetProvisionedCampSpeakers';
};

export type GetProvisionedCampSpeakersResponses = {
    /**
     * Camp speakers list
     */
    200: {
        data?: {
            currentUser?: {
                vehicles?: Array<{
                    id?: string;
                    connectedProducts?: Array<{
                        __typename?: string;
                        serialNumber?: string;
                        id?: string;
                    }>;
                }>;
            };
        };
    };
};

export type GetProvisionedCampSpeakersResponse = GetProvisionedCampSpeakersResponses[keyof GetProvisionedCampSpeakersResponses];

export type GetRegisteredWallboxesData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getRegisteredWallboxes';
};

export type GetRegisteredWallboxesResponses = {
    /**
     * Wallbox list
     */
    200: {
        data?: {
            getRegisteredWallboxes?: Array<WallboxRecord>;
        };
    };
};

export type GetRegisteredWallboxesResponse = GetRegisteredWallboxesResponses[keyof GetRegisteredWallboxesResponses];

export type GetWallboxStatusData = {
    body: {
        operationName?: string;
        variables?: {
            wallboxId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getWallboxStatus';
};

export type GetWallboxStatusResponses = {
    /**
     * Wallbox status
     */
    200: {
        data?: {
            getWallboxStatus?: WallboxRecord;
        };
    };
};

export type GetWallboxStatusResponse = GetWallboxStatusResponses[keyof GetWallboxStatusResponses];

export type UpdateWallboxData = {
    body: {
        operationName?: string;
        variables?: {
            wallboxId: string;
            name?: string;
            wifiId?: string;
            latitude?: string;
            longitude?: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#updateWallbox';
};

export type UpdateWallboxResponses = {
    /**
     * Updated wallbox
     */
    200: {
        data?: {
            updateWallbox?: WallboxRecord;
        };
    };
};

export type UpdateWallboxResponse = UpdateWallboxResponses[keyof UpdateWallboxResponses];

export type GetCompletedSessionSummariesData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getCompletedSessionSummaries';
};

export type GetCompletedSessionSummariesResponses = {
    /**
     * Session summaries
     */
    200: {
        data?: {
            getCompletedSessionSummaries?: Array<ChargingSessionSummary>;
        };
    };
};

export type GetCompletedSessionSummariesResponse = GetCompletedSessionSummariesResponses[keyof GetCompletedSessionSummariesResponses];

export type GetLiveSessionDataData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getLiveSessionData';
};

export type GetLiveSessionDataResponses = {
    /**
     * Live session data
     */
    200: {
        data?: {
            getLiveSessionData?: LiveSessionData;
        };
    };
};

export type GetLiveSessionDataResponse = GetLiveSessionDataResponses[keyof GetLiveSessionDataResponses];

export type GetLiveSessionHistoryData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getLiveSessionHistory';
};

export type GetLiveSessionHistoryResponses = {
    /**
     * Session history chart data
     */
    200: {
        data?: {
            getLiveSessionHistory?: {
                chartData?: Array<{
                    kw?: number;
                    time?: Date;
                }>;
            };
        };
    };
};

export type GetLiveSessionHistoryResponse = GetLiveSessionHistoryResponses[keyof GetLiveSessionHistoryResponses];

export type GetNonRivianUserSessionData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getNonRivianUserSession';
};

export type GetNonRivianUserSessionResponses = {
    /**
     * Non-Rivian session data
     */
    200: {
        data?: {
            getNonRivianUserSession?: {
                chargerId?: string | null;
                transactionId?: string | null;
                isRivianCharger?: boolean;
                vehicleChargerState?: {
                    value?: string;
                    updatedAt?: Date;
                } | null;
            } | null;
        };
    };
};

export type GetNonRivianUserSessionResponse = GetNonRivianUserSessionResponses[keyof GetNonRivianUserSessionResponses];

export type CheckByRivianIdData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#CheckByRivianId';
};

export type CheckByRivianIdResponses = {
    /**
     * Linked account status
     */
    200: {
        data?: {
            chargepoint?: {
                checkByRivianId?: boolean;
            };
        };
    };
};

export type CheckByRivianIdResponse = CheckByRivianIdResponses[keyof CheckByRivianIdResponses];

export type GetLinkedEmailForRivianIdData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/chrg/user/graphql#getLinkedEmailForRivianId';
};

export type GetLinkedEmailForRivianIdResponses = {
    /**
     * Linked email
     */
    200: {
        data?: {
            chargepoint?: {
                getLinkedEmailForRivianId?: {
                    email?: string;
                };
            };
        };
    };
};

export type GetLinkedEmailForRivianIdResponse = GetLinkedEmailForRivianIdResponses[keyof GetLinkedEmailForRivianIdResponses];

export type ChargerDetailsData = {
    body: {
        operationName?: string;
        variables?: {
            ids: Array<string>;
            userLocation?: {
                latitude?: number;
                longitude?: number;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#ChargerDetails';
};

export type ChargerDetailsResponses = {
    /**
     * Charger details
     */
    200: {
        data?: {
            chargerByIds?: Array<ChargerDetails>;
        };
    };
};

export type ChargerDetailsResponse = ChargerDetailsResponses[keyof ChargerDetailsResponses];

export type SetChargingScheduleData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
            chargingSchedules: Array<ChargingSchedule>;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#SetChargingSchedule';
};

export type SetChargingScheduleResponses = {
    /**
     * Schedule set
     */
    200: {
        data?: {
            setChargingSchedules?: {
                success?: boolean;
            };
        };
    };
};

export type SetChargingScheduleResponse = SetChargingScheduleResponses[keyof SetChargingScheduleResponses];

export type GetChargingScheduleData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetChargingSchedule';
};

export type GetChargingScheduleResponses = {
    /**
     * Charging schedules
     */
    200: {
        data?: {
            getVehicle?: {
                chargingSchedules?: Array<ChargingSchedule>;
            };
        };
    };
};

export type GetChargingScheduleResponse = GetChargingScheduleResponses[keyof GetChargingScheduleResponses];

export type EnrollPhoneData = {
    body: {
        operationName?: string;
        variables?: {
            attrs: {
                userId: string;
                vehicleId: string;
                /**
                 * PEM-encoded ECDH public key (secp256r1)
                 */
                publicKey: string;
                /**
                 * Phone model
                 */
                type: string;
                /**
                 * Phone name
                 */
                name: string;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#EnrollPhone';
};

export type EnrollPhoneResponses = {
    /**
     * Phone enrolled
     */
    200: {
        data?: {
            enrollPhone?: {
                __typename?: string;
                success?: boolean;
            };
        };
    };
};

export type EnrollPhoneResponse = EnrollPhoneResponses[keyof EnrollPhoneResponses];

export type DisenrollPhoneData = {
    body: {
        operationName?: string;
        variables?: {
            attrs: {
                enrollmentId: string;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#DisenrollPhone';
};

export type DisenrollPhoneResponses = {
    /**
     * Phone disenrolled
     */
    200: {
        data?: {
            disenrollPhone?: {
                __typename?: string;
                success?: boolean;
            };
        };
    };
};

export type DisenrollPhoneResponse = DisenrollPhoneResponses[keyof DisenrollPhoneResponses];

export type SendVehicleCommandData = {
    body: {
        operationName?: string;
        variables?: {
            attrs: {
                command: VehicleCommand;
                /**
                 * HMAC-SHA256 of "{command}{timestamp}" using phone private key
                 */
                hmac: string;
                /**
                 * Unix timestamp
                 */
                timestamp: number;
                vasPhoneId: string;
                deviceId: string;
                vehicleId: string;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#sendVehicleCommand';
};

export type SendVehicleCommandResponses = {
    /**
     * Command sent
     */
    200: {
        data?: {
            sendVehicleCommand?: {
                __typename?: string;
                id?: string;
                command?: string;
                state?: number;
            };
        };
    };
};

export type SendVehicleCommandResponse = SendVehicleCommandResponses[keyof SendVehicleCommandResponses];

export type GetVehicleCommandData = {
    body: {
        operationName?: string;
        variables?: {
            /**
             * Command ID returned from sendVehicleCommand
             */
            id: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#getVehicleCommand';
};

export type GetVehicleCommandResponses = {
    /**
     * Command status
     */
    200: {
        data?: {
            getVehicleCommand?: {
                __typename?: string;
                id?: string;
                command?: string;
                createdAt?: string;
                /**
                 * 0 = completed
                 */
                state?: number;
                responseCode?: string | null;
                statusCode?: string | null;
            };
        };
    };
};

export type GetVehicleCommandResponse = GetVehicleCommandResponses[keyof GetVehicleCommandResponses];

export type ParseAndShareLocationToVehicleData = {
    body: {
        operationName?: string;
        variables?: {
            /**
             * URL of the location to share
             */
            str: string;
            vehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#ParseAndShareLocationToVehicle';
};

export type ParseAndShareLocationToVehicleResponses = {
    /**
     * Location shared
     */
    200: {
        data?: {
            parseAndShareLocationToVehicle?: {
                __typename?: string;
                publishResponse?: {
                    __typename?: string;
                    result?: number;
                };
            };
        };
    };
};

export type ParseAndShareLocationToVehicleResponse = ParseAndShareLocationToVehicleResponses[keyof ParseAndShareLocationToVehicleResponses];

export type GetVehicleStateData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleID: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetVehicleState';
};

export type GetVehicleStateResponses = {
    /**
     * Vehicle state
     */
    200: {
        data?: {
            vehicleState?: VehicleState;
        };
    };
};

export type GetVehicleStateResponse = GetVehicleStateResponses[keyof GetVehicleStateResponses];

export type GetVehicleLastConnectionData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleID: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetVehicleLastConnection';
};

export type GetVehicleLastConnectionResponses = {
    /**
     * Last connection info
     */
    200: {
        data?: {
            vehicleState?: {
                cloudConnection?: {
                    lastSync?: Date;
                };
            };
        };
    };
};

export type GetVehicleLastConnectionResponse = GetVehicleLastConnectionResponses[keyof GetVehicleLastConnectionResponses];

export type GetVehicleData = {
    body: {
        operationName?: string;
        variables?: {
            getVehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetVehicle';
};

export type GetVehicleResponses = {
    /**
     * Vehicle details
     */
    200: {
        data?: {
            getVehicle?: {
                __typename?: string;
                invitedUsers?: Array<{
                    __typename?: 'ProvisionedUser' | 'UnprovisionedUser';
                    devices?: Array<{
                        type?: string;
                        mappedIdentityId?: string;
                        id?: string;
                        hrid?: string;
                        deviceName?: string;
                        isPaired?: boolean;
                        isEnabled?: boolean;
                    }>;
                    firstName?: string;
                    lastName?: string;
                    email?: string;
                    roles?: Array<string>;
                    userId?: string;
                }>;
            };
        };
    };
};

export type GetVehicleResponse = GetVehicleResponses[keyof GetVehicleResponses];

export type GetOtaUpdateDetailsData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#getOTAUpdateDetails';
};

export type GetOtaUpdateDetailsResponses = {
    /**
     * OTA update details
     */
    200: {
        data?: {
            getVehicle?: {
                availableOTAUpdateDetails?: {
                    url?: string;
                    version?: string;
                    locale?: string;
                } | null;
                currentOTAUpdateDetails?: {
                    url?: string;
                    version?: string;
                    locale?: string;
                } | null;
            };
        };
    };
};

export type GetOtaUpdateDetailsResponse = GetOtaUpdateDetailsResponses[keyof GetOtaUpdateDetailsResponses];

export type GetVehicleImagesData = {
    body: {
        operationName?: string;
        variables?: {
            extension: string;
            resolution: string;
            /**
             * Vehicle version number (try 1-5)
             */
            vehicleVersion: string;
        };
        query?: string;
    };
    headers: {
        'dc-cid': string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetVehicleImages';
};

export type GetVehicleImagesResponses = {
    /**
     * Vehicle images
     */
    200: {
        data?: {
            getVehicleOrderMobileImages?: Array<VehicleMobileImage>;
            getVehicleMobileImages?: Array<VehicleMobileImage>;
        };
    };
};

export type GetVehicleImagesResponse = GetVehicleImagesResponses[keyof GetVehicleImagesResponses];

export type GetEstimatedRangeData = {
    body: {
        operationName?: string;
        variables?: {
            /**
             * Battery percentage (0-100)
             */
            startSoc: number;
            vehicleId: string;
            driveMode?: string;
            trailerProfile?: string;
        };
        query?: string;
    };
    headers: {
        'dc-cid': string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetEstimatedRange';
};

export type GetEstimatedRangeResponses = {
    /**
     * Estimated range
     */
    200: {
        data?: {
            getVehicle?: {
                /**
                 * Range in kilometers
                 */
                estimatedRange?: number;
            };
        };
    };
};

export type GetEstimatedRangeResponse = GetEstimatedRangeResponses[keyof GetEstimatedRangeResponses];

export type SetVehicleNameData = {
    body: {
        operationName?: string;
        variables?: {
            vehicleId: string;
            name: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#SetVehicleName';
};

export type SetVehicleNameResponses = {
    /**
     * Name updated
     */
    200: {
        data?: {
            setVehicleName?: {
                value?: string;
            };
        };
    };
};

export type SetVehicleNameResponse = SetVehicleNameResponses[keyof SetVehicleNameResponses];

export type SupportedFeaturesData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/gateway/graphql#SupportedFeatures';
};

export type SupportedFeaturesResponses = {
    /**
     * Supported features
     */
    200: {
        data?: {
            currentUser?: {
                vehicles?: Array<{
                    id?: string;
                    vehicle?: {
                        vehicleState?: {
                            supportedFeatures?: Array<SupportedFeature>;
                        };
                    };
                }>;
            };
        };
    };
};

export type SupportedFeaturesResponse = SupportedFeaturesResponses[keyof SupportedFeaturesResponses];

export type RegisterPushNotificationTokenData = {
    body: {
        operationName?: string;
        variables?: {
            data: {
                locale: string;
                token: string;
                type: 'FCM';
                userId: string;
                mobileApp: string;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#RegisterPushNotificationToken';
};

export type RegisterPushNotificationTokenResponses = {
    /**
     * Token registered
     */
    200: {
        data?: {
            registerPushNotificationToken?: {
                deviceTokenId?: string;
                locale?: string;
                success?: boolean;
                token?: string;
            };
        };
    };
};

export type RegisterPushNotificationTokenResponse = RegisterPushNotificationTokenResponses[keyof RegisterPushNotificationTokenResponses];

export type GetVehicleWheelImageData = {
    body?: never;
    path: {
        /**
         * Wheel option ID (e.g. WHL-0AS, WHL-0A1, WHL-2SS)
         */
        wheelOption: string;
    };
    query?: never;
    url: '/mobile/static/img/v1/features/wheels/{wheelOption}.png';
};

export type GetVehicleWheelImageResponses = {
    /**
     * Wheel image
     */
    200: Blob | File;
};

export type GetVehicleWheelImageResponse = GetVehicleWheelImageResponses[keyof GetVehicleWheelImageResponses];

export type VehicleSubscriptionsData = {
    body?: never;
    headers: {
        'a-sess': string;
        'u-sess': string;
        'csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/gql-consumer-subscriptions/graphql';
};

export type PlacesData = {
    body: {
        operationName?: string;
        variables?: {
            params: {
                userLocation?: {
                    latitude?: number;
                    longitude?: number;
                };
                query: string;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#Places';
};

export type PlacesResponses = {
    /**
     * Place results
     */
    200: {
        data?: {
            places?: {
                dataProvider?: string;
                results?: Array<PlaceResult>;
            };
        };
    };
};

export type PlacesResponse = PlacesResponses[keyof PlacesResponses];

export type PlanTripData = {
    body: {
        operationName?: string;
        variables?: {
            waypoints: Array<{
                latitude: number;
                longitude: number;
                entityId?: string;
                waypointType: 'OTHER' | 'DC_CHARGE_STATION';
            }>;
            originBearing: number;
            vehicleId: string;
            startingSoc: number;
            startingRangeMeters?: number;
            targetArrivalSocPercent?: number;
            driveMode?: 'EVERYDAY' | 'SPORT' | 'CONSERVE';
            networkPreferences?: Array<{
                networkId?: string;
                preference?: number;
            }>;
            trailerProfile?: 'NONE';
            avoidAdapterRequired?: boolean;
            supportedConnectorTypes?: Array<'CCS' | 'J1772'>;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#planTripWithMultiStop';
};

export type PlanTripResponses = {
    /**
     * Trip plan
     */
    200: {
        data?: {
            planTripMultiStop?: TripPlanResult;
        };
    };
};

export type PlanTripResponse = PlanTripResponses[keyof PlanTripResponses];

export type SaveTripData = {
    body: {
        operationName?: string;
        variables?: {
            attrs: {
                name: string;
                startingSOC: number;
                stops: Array<{
                    name?: string;
                    location?: {
                        latitude?: number;
                        longitude?: number;
                    };
                    targetArrivalSOCPercent?: number;
                    type?: 'VEHICLE_LOCATION' | 'POI';
                    placeId?: {
                        value?: string;
                        dataProvider?: string;
                    };
                }>;
                driveMode?: string;
                networkPreferences?: Array<{
                    networkId?: string;
                    preference?: number;
                }>;
                trailerProfile?: string;
                avoidAdapterRequired?: boolean;
                /**
                 * Unix timestamp
                 */
                departureTime?: number;
            };
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#saveTrip';
};

export type SaveTripResponses = {
    /**
     * Trip saved
     */
    200: {
        data?: {
            /**
             * New trip ID
             */
            saveTrip?: string;
        };
    };
};

export type SaveTripResponse = SaveTripResponses[keyof SaveTripResponses];

export type GetSavedTripsData = {
    body: GraphQlRequest;
    path?: never;
    query?: never;
    url: '/gateway/graphql#getSavedTrips';
};

export type GetSavedTripsResponses = {
    /**
     * Saved trips
     */
    200: {
        data?: {
            getSavedTrips?: Array<{
                id?: string;
                name?: string;
                startingSOC?: number;
                stops?: Array<{
                    name?: string;
                    location?: {
                        latitude?: number;
                        longitude?: number;
                    };
                    targetArrivalSOCPercent?: number;
                    type?: string;
                    placeId?: {
                        value?: string;
                        dataProvider?: string;
                    };
                }>;
                driveMode?: string;
                networkPreferences?: Array<{
                    networkId?: string;
                    preference?: string;
                }>;
                trailerProfile?: string;
                avoidAdapterRequired?: boolean;
                createdAt?: string;
                updatedAt?: string;
                departureTime?: string;
            }>;
        };
    };
};

export type GetSavedTripsResponse = GetSavedTripsResponses[keyof GetSavedTripsResponses];

export type GetTrailerProfilesData = {
    body: {
        operationName?: string;
        variables?: {
            getVehicleId: string;
        };
        query?: string;
    };
    path?: never;
    query?: never;
    url: '/gateway/graphql#GetTrailerProfiles';
};

export type GetTrailerProfilesResponses = {
    /**
     * Trailer profiles
     */
    200: {
        data?: {
            getVehicle?: {
                trailerProfiles?: {
                    trailerDefault?: TrailerProfile;
                    trailer1?: TrailerProfile;
                    trailer2?: TrailerProfile;
                    trailer3?: TrailerProfile;
                } | null;
            };
        };
    };
};

export type GetTrailerProfilesResponse = GetTrailerProfilesResponses[keyof GetTrailerProfilesResponses];

export type SearchShopProductsBySkusData = {
    body: {
        operationName?: string;
        variables?: {
            country?: string;
            skus: Array<string>;
            pageInfo?: {
                from?: number;
                size?: number;
            };
        };
        query?: string;
    };
    headers: {
        'csrf-token': string;
        'dc-cid': string;
        'x-datadog-origin': string;
    };
    path?: never;
    query?: never;
    url: '/orders/graphql#SearchShopProductsBySkus';
};

export type SearchShopProductsBySkusResponses = {
    /**
     * Product search results
     */
    200: {
        data?: {
            searchProducts?: {
                total?: number;
                size?: number;
                from?: number;
                data?: Array<{
                    sku?: string;
                    title?: string;
                    brand?: string;
                    rivianShopStatus?: string;
                    price?: {
                        listPrice?: {
                            amount?: number;
                            currency?: string;
                        };
                    };
                    dimensionValues?: Array<{
                        name?: string;
                        valueName?: string;
                        localizedStrings?: string;
                    }>;
                    channels?: Array<{
                        [key: string]: unknown;
                    }>;
                    channelAttributes?: Array<{
                        attributeId?: string;
                        name?: string;
                        channel?: string;
                        value?: string;
                    }>;
                }>;
            };
        };
    };
};

export type SearchShopProductsBySkusResponse = SearchShopProductsBySkusResponses[keyof SearchShopProductsBySkusResponses];

export type SearchShopPricingBySkuData = {
    body: {
        operationName?: string;
        variables?: {
            country?: string;
            skus: Array<string>;
            pageInfo?: {
                from?: number;
                size?: number;
            };
        };
        query?: string;
    };
    headers: {
        'csrf-token': string;
        'dc-cid': string;
        'x-datadog-origin': string;
    };
    path?: never;
    query?: never;
    url: '/orders/graphql#SearchShopPricingBySku';
};

export type SearchShopPricingBySkuResponses = {
    /**
     * Pricing results
     */
    200: {
        data?: {
            searchProducts?: {
                total?: number;
                size?: number;
                from?: number;
                data?: Array<{
                    sku?: string;
                    price?: {
                        listPrice?: {
                            amount?: number;
                            currency?: string;
                        };
                    };
                }>;
            };
        };
    };
};

export type SearchShopPricingBySkuResponse = SearchShopPricingBySkuResponses[keyof SearchShopPricingBySkuResponses];

export type GetConfiguratorImageData = {
    body?: never;
    path: {
        vehicle: 'r1t' | 'r1s';
        view: 'front' | 'rear' | 'side' | 'driver' | 'backseats' | 'studio';
        /**
         * Comma-separated version and option codes (e.g. 2023.1,actbdg-brt,bat-c01,exp-lsv,gen-2,mot-201,pkg-adv,whl-2ss,studio)
         */
        options: string;
    };
    query?: never;
    url: '/rivian-main/c_fill,w_1920/c_crop,h_1100,g_south,y_178/compositor/{vehicle}/{view}/{options}';
};

export type GetConfiguratorImageResponses = {
    /**
     * Vehicle configuration image
     */
    200: Blob | File;
};

export type GetConfiguratorImageResponse = GetConfiguratorImageResponses[keyof GetConfiguratorImageResponses];
