// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zGraphQlRequest = z.object({
    operationName: z.string(),
    variables: z.record(z.unknown()).optional(),
    query: z.string()
});

export const zGraphQlResponse = z.object({
    data: z.record(z.unknown()).optional(),
    errors: z.array(z.object({
        message: z.string().optional()
    })).optional()
});

export const zCreateCsrfTokenResponse = z.object({
    data: z.object({
        createCsrfToken: z.object({
            __typename: z.string().optional(),
            csrfToken: z.string().optional(),
            appSessionToken: z.string().optional()
        }).optional()
    }).optional()
});

export const zLoginResponse = z.object({
    data: z.object({
        loginWithOTP: z.object({
            __typename: z.string().optional(),
            accessToken: z.string().optional(),
            refreshToken: z.string().optional(),
            userSessionToken: z.string().optional()
        }).optional()
    }).optional()
});

export const zMfaLoginResponse = z.object({
    data: z.object({
        login: z.object({
            __typename: z.string().optional(),
            otpToken: z.string().optional()
        }).optional()
    }).optional()
});

export const zUserAddress = z.object({
    __typename: z.string().optional(),
    id: z.string().optional(),
    types: z.array(z.enum(['PRIMARY', 'SHIPPING'])).optional(),
    line1: z.string().optional(),
    line2: z.string().nullish(),
    city: z.string().optional(),
    state: z.string().optional(),
    postalCode: z.string().optional(),
    country: z.string().optional()
});

export const zConfigOption = z.object({
    __typename: z.string().optional(),
    optionId: z.string().optional(),
    optionName: z.string().optional()
});

export const zMobileConfiguration = z.object({
    __typename: z.string().optional(),
    trimOption: zConfigOption.optional(),
    exteriorColorOption: zConfigOption.optional(),
    interiorColorOption: zConfigOption.optional(),
    driveSystemOption: zConfigOption.optional(),
    tonneauOption: zConfigOption.nullish(),
    wheelOption: zConfigOption.optional(),
    driveSystemDriveModes: z.array(z.string()).optional(),
    driveSystemTowingDriveModes: z.array(z.string()).optional(),
    maxVehiclePower: z.number().optional(),
    chargePort: z.enum(['CCS', 'J1772']).optional()
});

export const zMaintenanceSchedule = z.object({
    sections: z.array(z.object({
        items: z.array(z.object({
            description: z.string().optional(),
            isDue: z.boolean().nullish()
        })).optional(),
        serviceLifetime: z.union([
            z.object({
                __typename: z.string().optional(),
                km: z.number().int().optional(),
                mi: z.number().int().optional()
            }),
            z.object({
                __typename: z.string().optional(),
                year: z.number().int().optional()
            })
        ]).optional()
    })).optional()
});

export const zEnrolledPhone = z.object({
    vas: z.object({
        vasPhoneId: z.string().optional(),
        publicKey: z.string().optional()
    }).optional(),
    enrolled: z.array(z.object({
        deviceType: z.string().optional(),
        deviceName: z.string().optional(),
        vehicleId: z.string().optional(),
        identityId: z.string().optional(),
        shortName: z.string().optional()
    })).optional()
});

export const zPendingInvite = z.object({
    id: z.string().optional(),
    invitedByFirstName: z.string().optional(),
    role: z.string().optional(),
    status: z.string().optional(),
    vehicleId: z.string().optional(),
    vehicleModel: z.string().optional(),
    email: z.string().optional()
});

export const zTimestampedValue = z.object({
    timeStamp: z.string().datetime().optional(),
    value: z.union([
        z.string(),
        z.number(),
        z.boolean(),
        z.number().int()
    ]).optional()
}).nullable();

export const zSupportedFeature = z.object({
    name: z.string().optional(),
    status: z.enum(['AVAILABLE', 'UNAVAILABLE']).optional()
});

export const zVehicleState = z.object({
    __typename: z.string().optional(),
    gnssLocation: z.object({
        latitude: z.number().optional(),
        longitude: z.number().optional(),
        timeStamp: z.string().datetime().optional(),
        isAuthorized: z.boolean().optional()
    }).nullish(),
    gnssSpeed: zTimestampedValue.optional(),
    gnssAltitude: zTimestampedValue.optional(),
    gnssError: z.object({
        timeStamp: z.string().datetime().optional(),
        positionVertical: z.number().optional(),
        positionHorizontal: z.number().optional(),
        speed: z.number().optional(),
        bearing: z.number().optional()
    }).nullish(),
    alarmSoundStatus: zTimestampedValue.optional(),
    timeToEndOfCharge: zTimestampedValue.optional(),
    doorFrontLeftLocked: zTimestampedValue.optional(),
    doorFrontLeftClosed: zTimestampedValue.optional(),
    doorFrontRightLocked: zTimestampedValue.optional(),
    doorFrontRightClosed: zTimestampedValue.optional(),
    doorRearLeftLocked: zTimestampedValue.optional(),
    doorRearLeftClosed: zTimestampedValue.optional(),
    doorRearRightLocked: zTimestampedValue.optional(),
    doorRearRightClosed: zTimestampedValue.optional(),
    windowFrontLeftClosed: zTimestampedValue.optional(),
    windowFrontRightClosed: zTimestampedValue.optional(),
    windowFrontLeftCalibrated: zTimestampedValue.optional(),
    windowFrontRightCalibrated: zTimestampedValue.optional(),
    windowRearLeftCalibrated: zTimestampedValue.optional(),
    windowRearRightCalibrated: zTimestampedValue.optional(),
    windowRearLeftClosed: zTimestampedValue.optional(),
    windowRearRightClosed: zTimestampedValue.optional(),
    closureFrunkLocked: zTimestampedValue.optional(),
    closureFrunkClosed: zTimestampedValue.optional(),
    closureFrunkNextAction: zTimestampedValue.optional(),
    closureLiftgateLocked: zTimestampedValue.optional(),
    closureLiftgateClosed: zTimestampedValue.optional(),
    closureLiftgateNextAction: zTimestampedValue.optional(),
    closureSideBinLeftLocked: zTimestampedValue.optional(),
    closureSideBinLeftClosed: zTimestampedValue.optional(),
    closureSideBinRightLocked: zTimestampedValue.optional(),
    closureSideBinLeftNextAction: zTimestampedValue.optional(),
    closureSideBinRightClosed: zTimestampedValue.optional(),
    closureSideBinRightNextAction: zTimestampedValue.optional(),
    closureTailgateLocked: zTimestampedValue.optional(),
    closureTailgateClosed: zTimestampedValue.optional(),
    closureTailgateNextAction: zTimestampedValue.optional(),
    closureTonneauLocked: zTimestampedValue.optional(),
    closureTonneauClosed: zTimestampedValue.optional(),
    gearGuardLocked: zTimestampedValue.optional(),
    wiperFluidState: zTimestampedValue.optional(),
    powerState: zTimestampedValue.optional(),
    batteryHvThermalEventPropagation: zTimestampedValue.optional(),
    twelveVoltBatteryHealth: zTimestampedValue.optional(),
    vehicleMileage: zTimestampedValue.optional(),
    brakeFluidLow: zTimestampedValue.optional(),
    gearStatus: zTimestampedValue.optional(),
    tirePressureStatusFrontLeft: zTimestampedValue.optional(),
    tirePressureStatusValidFrontLeft: zTimestampedValue.optional(),
    tirePressureStatusFrontRight: zTimestampedValue.optional(),
    tirePressureStatusValidFrontRight: zTimestampedValue.optional(),
    tirePressureStatusRearLeft: zTimestampedValue.optional(),
    tirePressureStatusValidRearLeft: zTimestampedValue.optional(),
    tirePressureStatusRearRight: zTimestampedValue.optional(),
    tirePressureStatusValidRearRight: zTimestampedValue.optional(),
    batteryLevel: zTimestampedValue.optional(),
    chargerState: zTimestampedValue.optional(),
    batteryLimit: zTimestampedValue.optional(),
    remoteChargingAvailable: zTimestampedValue.optional(),
    batteryHvThermalEvent: zTimestampedValue.optional(),
    rangeThreshold: zTimestampedValue.optional(),
    distanceToEmpty: zTimestampedValue.optional(),
    otaAvailableVersion: zTimestampedValue.optional(),
    otaAvailableVersionGitHash: zTimestampedValue.optional(),
    otaAvailableVersionNumber: zTimestampedValue.optional(),
    otaAvailableVersionWeek: zTimestampedValue.optional(),
    otaAvailableVersionYear: zTimestampedValue.optional(),
    otaCurrentVersion: zTimestampedValue.optional(),
    otaCurrentVersionGitHash: zTimestampedValue.optional(),
    otaCurrentVersionNumber: zTimestampedValue.optional(),
    otaCurrentVersionWeek: zTimestampedValue.optional(),
    otaCurrentVersionYear: zTimestampedValue.optional(),
    otaDownloadProgress: zTimestampedValue.optional(),
    otaInstallDuration: zTimestampedValue.optional(),
    otaInstallProgress: zTimestampedValue.optional(),
    otaInstallReady: zTimestampedValue.optional(),
    otaInstallTime: zTimestampedValue.optional(),
    otaInstallType: zTimestampedValue.optional(),
    otaStatus: zTimestampedValue.optional(),
    otaCurrentStatus: zTimestampedValue.optional(),
    cabinClimateInteriorTemperature: zTimestampedValue.optional(),
    cabinPreconditioningStatus: zTimestampedValue.optional(),
    cabinPreconditioningType: zTimestampedValue.optional(),
    petModeStatus: zTimestampedValue.optional(),
    petModeTemperatureStatus: zTimestampedValue.optional(),
    cabinClimateDriverTemperature: zTimestampedValue.optional(),
    gearGuardVideoStatus: zTimestampedValue.optional(),
    gearGuardVideoMode: zTimestampedValue.optional(),
    gearGuardVideoTermsAccepted: zTimestampedValue.optional(),
    defrostDefogStatus: zTimestampedValue.optional(),
    steeringWheelHeat: zTimestampedValue.optional(),
    seatFrontLeftHeat: zTimestampedValue.optional(),
    seatFrontRightHeat: zTimestampedValue.optional(),
    seatRearLeftHeat: zTimestampedValue.optional(),
    seatRearRightHeat: zTimestampedValue.optional(),
    chargerStatus: zTimestampedValue.optional(),
    seatFrontLeftVent: zTimestampedValue.optional(),
    seatFrontRightVent: zTimestampedValue.optional(),
    chargerDerateStatus: zTimestampedValue.optional(),
    driveMode: zTimestampedValue.optional(),
    serviceMode: zTimestampedValue.optional(),
    trailerStatus: zTimestampedValue.optional(),
    carWashMode: zTimestampedValue.optional(),
    chargePortState: zTimestampedValue.optional(),
    windowsNextAction: zTimestampedValue.optional(),
    btmFfHardwareFailureStatus: zTimestampedValue.optional(),
    btmIcHardwareFailureStatus: zTimestampedValue.optional(),
    btmLfdHardwareFailureStatus: zTimestampedValue.optional(),
    btmRfHardwareFailureStatus: zTimestampedValue.optional(),
    btmRfdHardwareFailureStatus: zTimestampedValue.optional(),
    chargingTimeEstimationValidity: zTimestampedValue.optional(),
    limitedAccelCold: zTimestampedValue.optional(),
    limitedRegenCold: zTimestampedValue.optional(),
    rearHitchStatus: zTimestampedValue.optional(),
    tirePressureFrontLeft: zTimestampedValue.optional(),
    tirePressureFrontRight: zTimestampedValue.optional(),
    tirePressureRearLeft: zTimestampedValue.optional(),
    tirePressureRearRight: zTimestampedValue.optional(),
    batteryCapacity: zTimestampedValue.optional(),
    supportedFeatures: z.array(zSupportedFeature).optional()
});

export const zVehicleDetails = z.object({
    __typename: z.string().optional(),
    model: z.enum(['R1T', 'R1S']).optional(),
    modelYear: z.number().int().optional(),
    mobileConfiguration: zMobileConfiguration.optional(),
    deviceSlots: z.object({
        phone: z.object({
            max: z.number().int().optional(),
            free: z.number().int().optional()
        }).optional()
    }).optional(),
    cccCapable: z.boolean().optional(),
    cccReady: z.boolean().optional(),
    cccEnabled: z.boolean().optional(),
    legacyEnabled: z.boolean().optional(),
    otaEarlyAccessStatus: z.boolean().optional(),
    vehicleState: zVehicleState.optional(),
    maintenanceSchedule: zMaintenanceSchedule.optional()
});

export const zUserVehicle = z.object({
    __typename: z.string().optional(),
    id: z.string().optional(),
    name: z.string().nullish(),
    owner: z.string().nullish(),
    roles: z.array(z.string()).optional(),
    vin: z.string().optional(),
    vas: z.object({
        vasVehicleId: z.string().optional(),
        vehiclePublicKey: z.string().optional()
    }).optional(),
    vehicle: zVehicleDetails.optional(),
    settings: z.object({
        name: z.object({
            value: z.string().nullish()
        }).nullish()
    }).optional()
});

export const zUserInfo = z.object({
    __typename: z.string().optional(),
    id: z.string().optional(),
    firstName: z.string().optional(),
    lastName: z.string().optional(),
    email: z.string().optional(),
    address: zUserAddress.nullish(),
    vehicles: z.array(zUserVehicle).optional(),
    enrolledPhones: z.array(zEnrolledPhone).optional(),
    pendingInvites: z.array(zPendingInvite).optional()
});

export const zTrailerProfile = z.object({
    __typename: z.string().optional(),
    rangeStatus: z.string().optional(),
    weight: z.number().optional(),
    onRoadEfficiency: z.number().optional(),
    offRoadEfficiency: z.number().optional(),
    name: z.string().optional()
}).nullable();

export const zTransactionStep = z.object({
    sourceStatus: z.object({
        status: z.string().optional(),
        details: z.record(z.unknown()).nullish()
    }).optional(),
    consumerStatus: z.object({
        displayOrder: z.number().int().optional(),
        current: z.boolean().optional(),
        complete: z.boolean().optional(),
        locked: z.boolean().optional(),
        inProgress: z.boolean().optional(),
        notStarted: z.boolean().optional(),
        error: z.boolean().optional()
    }).optional()
});

export const zVehicleCommand = z.enum([
    'WAKE_VEHICLE',
    'OPEN_FRUNK',
    'CLOSE_FRUNK',
    'OPEN_ALL_WINDOWS',
    'CLOSE_ALL_WINDOWS',
    'UNLOCK_ALL_CLOSURES',
    'LOCK_ALL_CLOSURES',
    'ENABLE_GEAR_GUARD_VIDEO',
    'DISABLE_GEAR_GUARD_VIDEO',
    'HONK_AND_FLASH_LIGHTS',
    'OPEN_TONNEAU_COVER',
    'CLOSE_TONNEAU_COVER'
]);

export const zWallboxRecord = z.object({
    __typename: z.string().optional(),
    wallboxId: z.string().optional(),
    userId: z.string().optional(),
    wifiId: z.string().optional(),
    name: z.string().optional(),
    linked: z.boolean().optional(),
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    chargingStatus: z.enum([
        'AVAILABLE',
        'CHARGING',
        'DISCONNECTED'
    ]).optional(),
    power: z.number().nullish(),
    currentVoltage: z.number().nullish(),
    currentAmps: z.number().nullish(),
    softwareVersion: z.string().optional(),
    model: z.string().optional(),
    serialNumber: z.string().optional(),
    maxPower: z.string().optional(),
    maxVoltage: z.string().optional(),
    maxAmps: z.string().nullish()
});

export const zChargingSessionSummary = z.object({
    chargerType: z.string().optional(),
    currencyCode: z.string().nullish(),
    paidTotal: z.number().nullish(),
    startInstant: z.string().datetime().optional(),
    endInstant: z.string().datetime().optional(),
    totalEnergyKwh: z.number().optional(),
    rangeAddedKm: z.number().nullish(),
    city: z.string().optional(),
    transactionId: z.string().optional(),
    vehicleId: z.string().nullish(),
    vehicleName: z.string().nullish(),
    vendor: z.string().optional(),
    isRoamingNetwork: z.boolean().optional(),
    isPublic: z.boolean().optional(),
    isHomeCharger: z.boolean().optional(),
    meta: z.object({
        transactionIdGroupingKey: z.string().optional(),
        dataSources: z.array(z.string()).optional()
    }).optional()
});

export const zLiveSessionData = z.object({
    isRivianCharger: z.boolean().nullish(),
    isFreeSession: z.boolean().nullish(),
    vehicleChargerState: zTimestampedValue.nullish(),
    chargerId: z.string().nullish(),
    startTime: z.string().datetime().nullish(),
    timeElapsed: z.string().nullish(),
    timeRemaining: zTimestampedValue.nullish(),
    kilometersChargedPerHour: zTimestampedValue.nullish(),
    power: zTimestampedValue.nullish(),
    rangeAddedThisSession: zTimestampedValue.nullish(),
    totalChargedEnergy: zTimestampedValue.nullish(),
    currentPrice: z.number().nullish()
});

export const zChargingSchedule = z.object({
    startTime: z.number().int().optional(),
    duration: z.number().int().optional(),
    location: z.object({
        latitude: z.number().optional(),
        longitude: z.number().optional()
    }).optional(),
    amperage: z.number().int().optional(),
    enabled: z.boolean().optional(),
    weekDays: z.array(z.enum([
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday'
    ])).optional()
});

export const zChargerDetails = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    location: z.object({
        addressComponents: z.array(z.object({
            type: z.string().optional(),
            shortName: z.string().optional(),
            longName: z.string().optional()
        })).optional(),
        formattedAddress: z.string().optional(),
        coordinate: z.object({
            latitude: z.number().optional(),
            longitude: z.number().optional()
        }).optional(),
        navCoordinate: z.object({
            latitude: z.number().optional(),
            longitude: z.number().optional()
        }).optional()
    }).optional(),
    distance: z.number().optional(),
    driveDetails: z.object({
        driveDistance: z.number().optional(),
        driveDuration: z.number().optional(),
        detourDistance: z.number().optional(),
        detourDuration: z.number().optional()
    }).nullish(),
    chargingStation: z.object({
        network: z.string().optional(),
        networkId: z.string().optional(),
        maxKw: z.number().int().optional(),
        note: z.string().optional(),
        chargers: z.array(z.object({
            locationId: z.string().optional(),
            pluginDependency: z.string().optional(),
            connectors: z.array(z.object({
                id: z.string().optional(),
                evseId: z.string().optional(),
                evseUid: z.string().optional(),
                name: z.string().optional(),
                level: z.string().optional(),
                maxKw: z.number().int().optional(),
                chargingPrice: z.object({
                    level: z.string().nullish(),
                    description: z.string().nullish(),
                    amount: z.number().nullish(),
                    currency: z.string().nullish(),
                    lastUpdateTime: z.string().nullish(),
                    symbol: z.string().nullish(),
                    type: z.string().nullish(),
                    unit: z.string().nullish()
                }).nullish(),
                type: z.enum(['CCS', 'J1772']).optional(),
                free: z.boolean().optional(),
                vend: z.string().nullish(),
                state: z.string().optional()
            })).optional()
        })).optional(),
        operatingHours: z.object({
            alwaysOpen: z.boolean().optional(),
            hours: z.array(z.object({
                close: z.number().int().optional(),
                day: z.string().optional(),
                open: z.number().int().optional()
            })).optional()
        }).optional()
    }).optional(),
    adapterRequired: z.boolean().optional()
});

export const zDelivery = z.object({
    __typename: z.string().optional(),
    status: z.string().optional(),
    carrier: z.string().optional(),
    deliveryAddress: z.object({
        addressLine1: z.string().optional(),
        addressLine2: z.string().nullish(),
        city: z.string().optional(),
        state: z.string().optional(),
        country: z.string().optional(),
        zipcode: z.string().optional()
    }).optional(),
    appointmentDetails: z.object({
        appointmentId: z.string().optional(),
        startDateTime: z.string().datetime().optional(),
        endDateTime: z.string().datetime().optional(),
        timeZone: z.string().optional()
    }).optional(),
    vehicleVIN: z.string().optional()
});

export const zOrderSnapshot = z.object({
    id: z.string().optional(),
    type: z.enum([
        'PRE_ORDER',
        'VEHICLE',
        'RETAIL'
    ]).optional(),
    orderDate: z.string().optional(),
    state: z.string().optional(),
    configurationStatus: z.string().nullish(),
    fulfillmentSummaryStatus: z.string().nullish(),
    total: z.number().optional(),
    paidTotal: z.number().optional(),
    subtotal: z.number().optional(),
    currency: z.string().optional(),
    consumerStatuses: z.object({
        isConsumerFlowComplete: z.boolean().optional()
    }).nullish(),
    items: z.array(z.object({
        id: z.string().optional(),
        title: z.string().optional(),
        type: z.string().optional(),
        sku: z.string().optional()
    })).optional()
});

export const zTripPlanResult = z.object({
    routes: z.array(z.object({
        routeResponse: z.record(z.unknown()).optional(),
        destinationReached: z.boolean().optional(),
        totalChargingDuration: z.number().int().optional(),
        arrivalSOC: z.number().int().optional(),
        arrivalReachableDistance: z.number().int().optional(),
        energyConsumptionOnLeg: z.number().nullish(),
        batteryEmptyToDestinationDistance: z.number().nullish(),
        batteryEmptyLocationLatitude: z.number().nullish(),
        batteryEmptyLocationLongitude: z.number().nullish(),
        waypoints: z.array(z.object({
            waypointType: z.enum(['DC_CHARGE_STATION', 'OTHER']).optional(),
            entityId: z.string().optional(),
            name: z.string().nullish(),
            latitude: z.number().optional(),
            longitude: z.number().optional(),
            maxPower: z.number().int().nullish(),
            chargeDuration: z.number().int().optional(),
            arrivalSOC: z.number().int().optional(),
            arrivalReachableDistance: z.number().int().optional(),
            departureSOC: z.number().int().optional(),
            departureReachableDistance: z.number().int().optional(),
            adapterRequired: z.boolean().nullish()
        })).optional()
    })).optional(),
    tripPlanStatus: z.string().optional(),
    chargeStationsAvailable: z.boolean().optional(),
    socBelowLimit: z.boolean().optional()
});

export const zPlaceResult = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    distance: z.number().optional(),
    location: z.object({
        addressComponents: z.array(z.object({
            type: z.string().optional(),
            shortName: z.string().optional(),
            longName: z.string().optional()
        })).optional(),
        coordinate: z.object({
            latitude: z.number().optional(),
            longitude: z.number().optional()
        }).optional(),
        navCoordinate: z.object({
            latitude: z.number().optional(),
            longitude: z.number().optional()
        }).optional(),
        formattedAddress: z.string().optional()
    }).optional(),
    driveDetails: z.object({
        driveDistance: z.number().optional(),
        driveDuration: z.number().optional(),
        detourDistance: z.number().optional(),
        detourDuration: z.number().optional()
    }).optional()
});

export const zVehicleMobileImage = z.object({
    __typename: z.string().optional(),
    vehicleId: z.string().optional(),
    orderId: z.string().optional(),
    url: z.string().url().optional(),
    resolution: z.string().optional(),
    size: z.enum(['small', 'large']).optional(),
    design: z.enum(['dark', 'light']).optional(),
    placement: z.enum([
        'front',
        'rear',
        'side',
        'side-charging',
        'overhead'
    ]).optional(),
    overlays: z.array(z.object({
        url: z.string().optional(),
        overlay: z.string().optional(),
        zIndex: z.number().int().optional()
    })).nullish()
});

export const zCreateCsrfTokenData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.array(z.unknown()).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * CSRF token created
 */
export const zCreateCsrfTokenResponse2 = zCreateCsrfTokenResponse;

export const zLoginData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            email: z.string().optional(),
            password: z.string().optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'a-sess': z.string(),
        'csrf-token': z.string(),
        'apollographql-client-name': z.string()
    })
});

/**
 * Login successful or MFA required
 */
export const zLoginResponse2 = z.union([
    zLoginResponse,
    zMfaLoginResponse
]);

export const zLoginWithOtpData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            email: z.string().optional(),
            otpCode: z.string().optional(),
            otpToken: z.string().optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'a-sess': z.string(),
        'csrf-token': z.string(),
        'apollographql-client-name': z.string()
    })
});

/**
 * MFA login successful
 */
export const zLoginWithOtpResponse = zLoginResponse;

export const zGetUserInfoData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.record(z.unknown()).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User info retrieved
 */
export const zGetUserInfoResponse = z.object({
    data: z.object({
        currentUser: zUserInfo.optional()
    }).optional()
});

export const zCurrentUserForLoginData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Current user details
 */
export const zCurrentUserForLoginResponse = z.object({
    data: z.object({
        currentUser: zUserInfo.optional()
    }).optional()
});

export const zVehicleOrdersData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Vehicle orders list
 */
export const zVehicleOrdersResponse = z.object({
    data: z.object({
        orders: z.object({
            data: z.array(zOrderSnapshot).optional()
        }).optional()
    }).nullish()
});

export const zDeliveryData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            orderId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Delivery info
 */
export const zDeliveryResponse = z.object({
    data: z.object({
        delivery: zDelivery.optional()
    }).optional()
});

export const zOrderData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            orderId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Order details
 */
export const zOrderResponse = z.object({
    data: z.object({
        order: z.object({
            vin: z.string().nullish(),
            state: z.string().optional(),
            billingAddress: z.object({
                firstName: z.string().optional(),
                lastName: z.string().optional(),
                line1: z.string().optional(),
                line2: z.string().nullish(),
                city: z.string().optional(),
                state: z.string().optional(),
                country: z.string().optional(),
                postalCode: z.string().optional()
            }).optional(),
            shippingAddress: z.object({
                firstName: z.string().optional(),
                lastName: z.string().optional(),
                line1: z.string().optional(),
                line2: z.string().nullish(),
                city: z.string().optional(),
                state: z.string().optional(),
                country: z.string().optional(),
                postalCode: z.string().optional()
            }).optional(),
            orderCancelDate: z.string().nullish(),
            orderEmail: z.string().optional(),
            currency: z.string().optional(),
            locale: z.string().optional(),
            storeId: z.string().optional(),
            type: z.string().optional(),
            subtotal: z.number().optional(),
            discountTotal: z.number().optional(),
            taxTotal: z.number().optional(),
            feesTotal: z.number().optional(),
            paidTotal: z.number().optional(),
            remainingTotal: z.number().optional(),
            outstandingBalance: z.number().optional(),
            costAfterCredits: z.number().optional(),
            total: z.number().optional(),
            payments: z.array(z.object({
                id: z.string().optional(),
                intent: z.string().optional(),
                date: z.string().optional(),
                method: z.string().optional(),
                amount: z.number().optional(),
                referenceNumber: z.string().nullish(),
                status: z.string().optional(),
                card: z.object({
                    last4: z.string().optional(),
                    expiryDate: z.string().optional(),
                    brand: z.string().optional()
                }).nullish(),
                bank: z.object({
                    bankName: z.string().optional(),
                    country: z.string().optional(),
                    last4: z.string().optional()
                }).nullish(),
                transactionNotes: z.string().nullish()
            })).optional(),
            tradeIns: z.array(z.object({
                tradeInReferenceId: z.string().optional(),
                amount: z.number().optional()
            })).optional(),
            vehicle: z.object({
                vehicleId: z.string().optional(),
                vin: z.string().nullish(),
                modelYear: z.number().int().optional(),
                model: z.string().optional(),
                make: z.string().optional()
            }).nullish(),
            items: z.array(z.object({
                id: z.string().optional(),
                subtotal: z.number().optional(),
                quantity: z.number().int().optional(),
                title: z.string().optional(),
                productId: z.string().optional(),
                type: z.string().optional(),
                unitPrice: z.number().optional(),
                sku: z.string().optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zSearchOrdersData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            orderTypes: z.array(z.string()).optional(),
            orderStates: z.array(z.string()).nullish(),
            dateRange: z.record(z.unknown()).nullish(),
            pageInfo: z.object({
                from: z.number().int().optional(),
                size: z.number().int().optional()
            }).optional(),
            sortFields: z.object({
                orderDate: z.enum(['ASC', 'DESC']).optional()
            }).optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Search results
 */
export const zSearchOrdersResponse = z.object({
    data: z.object({
        searchOrders: z.object({
            total: z.number().int().optional(),
            data: z.array(zOrderSnapshot).optional()
        }).optional()
    }).optional()
});

export const zUserData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User info
 */
export const zUserResponse = z.object({
    data: z.object({
        user: z.object({
            email: z.object({
                email: z.string().optional()
            }).optional(),
            phone: z.object({
                formatted: z.string().optional()
            }).nullish(),
            firstName: z.string().optional(),
            lastName: z.string().optional(),
            addresses: z.array(z.object({
                id: z.string().optional(),
                type: z.array(z.string()).optional(),
                line1: z.string().optional(),
                line2: z.string().nullish(),
                city: z.string().optional(),
                state: z.string().optional(),
                country: z.string().optional(),
                postalCode: z.string().optional()
            })).optional(),
            newsletterSubscription: z.boolean().optional(),
            smsSubscription: z.boolean().optional(),
            registrationChannels2FA: z.record(z.unknown()).optional(),
            userId: z.string().optional(),
            vehicles: z.array(z.record(z.unknown())).optional(),
            invites: z.array(z.record(z.unknown())).optional(),
            orderSnapshots: z.array(zOrderSnapshot).optional()
        }).optional()
    }).optional()
});

export const zPaymentMethodsData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Payment methods
 */
export const zPaymentMethodsResponse = z.object({
    data: z.object({
        paymentMethods: z.array(z.object({
            id: z.string().optional(),
            type: z.string().optional(),
            default: z.boolean().optional(),
            card: z.object({
                lastFour: z.string().optional(),
                brand: z.string().optional(),
                expiration: z.string().optional(),
                postalCode: z.string().optional()
            }).optional()
        })).optional()
    }).optional()
});

export const zTransactionStatusData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            orderId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Transaction statuses
 */
export const zTransactionStatusResponse = z.object({
    data: z.object({
        transactionStatus: z.object({
            titleAndReg: zTransactionStep.optional(),
            tradeIn: zTransactionStep.optional(),
            finance: zTransactionStep.optional(),
            delivery: zTransactionStep.optional(),
            insurance: zTransactionStep.optional(),
            documentUpload: zTransactionStep.optional(),
            contracts: zTransactionStep.optional(),
            payment: zTransactionStep.optional()
        }).optional()
    }).optional()
});

export const zFinanceSummaryData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            orderId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Finance summary
 */
export const zFinanceSummaryResponse = z.object({
    data: z.object({
        financeSummary: z.object({
            orderId: z.string().optional(),
            status: z.string().optional(),
            financeChoice: z.object({
                financeChoice: z.string().optional(),
                institutionName: z.string().nullish(),
                paymentMethod: z.string().optional(),
                trackingNumber: z.string().nullish(),
                preApprovedAmount: z.string().optional(),
                loanOfficerName: z.string().nullish(),
                loanOfficerContact: z.string().nullish(),
                downPayment: z.string().optional(),
                rate: z.number().optional(),
                term: z.number().int().optional(),
                rateAndTermSkipped: z.boolean().optional()
            }).optional()
        }).optional()
    }).optional()
});

export const zGetProvisionedCampSpeakersData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Camp speakers list
 */
export const zGetProvisionedCampSpeakersResponse = z.object({
    data: z.object({
        currentUser: z.object({
            vehicles: z.array(z.object({
                id: z.string().optional(),
                connectedProducts: z.array(z.object({
                    __typename: z.string().optional(),
                    serialNumber: z.string().optional(),
                    id: z.string().optional()
                })).optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zGetRegisteredWallboxesData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Wallbox list
 */
export const zGetRegisteredWallboxesResponse = z.object({
    data: z.object({
        getRegisteredWallboxes: z.array(zWallboxRecord).optional()
    }).optional()
});

export const zGetWallboxStatusData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            wallboxId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Wallbox status
 */
export const zGetWallboxStatusResponse = z.object({
    data: z.object({
        getWallboxStatus: zWallboxRecord.optional()
    }).optional()
});

export const zUpdateWallboxData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            wallboxId: z.string(),
            name: z.string().optional(),
            wifiId: z.string().optional(),
            latitude: z.string().optional(),
            longitude: z.string().optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Updated wallbox
 */
export const zUpdateWallboxResponse = z.object({
    data: z.object({
        updateWallbox: zWallboxRecord.optional()
    }).optional()
});

export const zGetCompletedSessionSummariesData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Session summaries
 */
export const zGetCompletedSessionSummariesResponse = z.object({
    data: z.object({
        getCompletedSessionSummaries: z.array(zChargingSessionSummary).optional()
    }).optional()
});

export const zGetLiveSessionDataData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Live session data
 */
export const zGetLiveSessionDataResponse = z.object({
    data: z.object({
        getLiveSessionData: zLiveSessionData.optional()
    }).optional()
});

export const zGetLiveSessionHistoryData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Session history chart data
 */
export const zGetLiveSessionHistoryResponse = z.object({
    data: z.object({
        getLiveSessionHistory: z.object({
            chartData: z.array(z.object({
                kw: z.number().optional(),
                time: z.string().datetime().optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zGetNonRivianUserSessionData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Non-Rivian session data
 */
export const zGetNonRivianUserSessionResponse = z.object({
    data: z.object({
        getNonRivianUserSession: z.object({
            chargerId: z.string().nullish(),
            transactionId: z.string().nullish(),
            isRivianCharger: z.boolean().optional(),
            vehicleChargerState: z.object({
                value: z.string().optional(),
                updatedAt: z.string().datetime().optional()
            }).nullish()
        }).nullish()
    }).optional()
});

export const zCheckByRivianIdData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Linked account status
 */
export const zCheckByRivianIdResponse = z.object({
    data: z.object({
        chargepoint: z.object({
            checkByRivianId: z.boolean().optional()
        }).optional()
    }).optional()
});

export const zGetLinkedEmailForRivianIdData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Linked email
 */
export const zGetLinkedEmailForRivianIdResponse = z.object({
    data: z.object({
        chargepoint: z.object({
            getLinkedEmailForRivianId: z.object({
                email: z.string().nullish()
            }).nullish()
        }).optional()
    }).optional()
});

export const zChargerDetailsData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            ids: z.array(z.string()),
            userLocation: z.object({
                latitude: z.number().optional(),
                longitude: z.number().optional()
            }).optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Charger details
 */
export const zChargerDetailsResponse = z.object({
    data: z.object({
        chargerByIds: z.array(zChargerDetails).optional()
    }).optional()
});

export const zSetChargingScheduleData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string(),
            chargingSchedules: z.array(zChargingSchedule)
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Schedule set
 */
export const zSetChargingScheduleResponse = z.object({
    data: z.object({
        setChargingSchedules: z.object({
            success: z.boolean().optional()
        }).optional()
    }).optional()
});

export const zGetChargingScheduleData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Charging schedules
 */
export const zGetChargingScheduleResponse = z.object({
    data: z.object({
        getVehicle: z.object({
            chargingSchedules: z.array(zChargingSchedule).nullish()
        }).optional()
    }).optional()
});

export const zEnrollPhoneData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            attrs: z.object({
                userId: z.string(),
                vehicleId: z.string(),
                publicKey: z.string(),
                type: z.string(),
                name: z.string()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Phone enrolled
 */
export const zEnrollPhoneResponse = z.object({
    data: z.object({
        enrollPhone: z.object({
            __typename: z.string().optional(),
            success: z.boolean().optional()
        }).optional()
    }).optional()
});

export const zDisenrollPhoneData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            attrs: z.object({
                enrollmentId: z.string()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Phone disenrolled
 */
export const zDisenrollPhoneResponse = z.object({
    data: z.object({
        disenrollPhone: z.object({
            __typename: z.string().optional(),
            success: z.boolean().optional()
        }).optional()
    }).optional()
});

export const zSendVehicleCommandData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            attrs: z.object({
                command: zVehicleCommand,
                hmac: z.string(),
                timestamp: z.number().int(),
                vasPhoneId: z.string(),
                deviceId: z.string(),
                vehicleId: z.string()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Command sent
 */
export const zSendVehicleCommandResponse = z.object({
    data: z.object({
        sendVehicleCommand: z.object({
            __typename: z.string().optional(),
            id: z.string().optional(),
            command: z.string().optional(),
            state: z.number().int().optional()
        }).optional()
    }).optional()
});

export const zGetVehicleCommandData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            id: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Command status
 */
export const zGetVehicleCommandResponse = z.object({
    data: z.object({
        getVehicleCommand: z.object({
            __typename: z.string().optional(),
            id: z.string().optional(),
            command: z.string().optional(),
            createdAt: z.string().optional(),
            state: z.number().int().optional(),
            responseCode: z.string().nullish(),
            statusCode: z.string().nullish()
        }).optional()
    }).optional()
});

export const zParseAndShareLocationToVehicleData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            str: z.string(),
            vehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Location shared
 */
export const zParseAndShareLocationToVehicleResponse = z.object({
    data: z.object({
        parseAndShareLocationToVehicle: z.object({
            __typename: z.string().optional(),
            publishResponse: z.object({
                __typename: z.string().optional(),
                result: z.number().int().optional()
            }).optional()
        }).optional()
    }).optional()
});

export const zGetVehicleStateData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleID: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Vehicle state
 */
export const zGetVehicleStateResponse = z.object({
    data: z.object({
        vehicleState: zVehicleState.optional()
    }).optional()
});

export const zGetVehicleLastConnectionData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleID: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Last connection info
 */
export const zGetVehicleLastConnectionResponse = z.object({
    data: z.object({
        vehicleState: z.object({
            cloudConnection: z.object({
                lastSync: z.string().datetime().optional()
            }).optional()
        }).optional()
    }).optional()
});

export const zGetVehicleData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            getVehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Vehicle details
 */
export const zGetVehicleResponse = z.object({
    data: z.object({
        getVehicle: z.object({
            __typename: z.string().optional(),
            invitedUsers: z.array(z.object({
                __typename: z.enum(['ProvisionedUser', 'UnprovisionedUser']).optional(),
                devices: z.array(z.object({
                    type: z.string().optional(),
                    mappedIdentityId: z.string().optional(),
                    id: z.string().optional(),
                    hrid: z.string().nullish(),
                    deviceName: z.string().optional(),
                    isPaired: z.boolean().optional(),
                    isEnabled: z.boolean().optional()
                })).optional(),
                firstName: z.string().optional(),
                lastName: z.string().optional(),
                email: z.string().optional(),
                roles: z.array(z.string()).optional(),
                userId: z.string().optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zGetOtaUpdateDetailsData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OTA update details
 */
export const zGetOtaUpdateDetailsResponse = z.object({
    data: z.object({
        getVehicle: z.object({
            availableOTAUpdateDetails: z.object({
                url: z.string().optional(),
                version: z.string().optional(),
                locale: z.string().optional()
            }).nullish(),
            currentOTAUpdateDetails: z.object({
                url: z.string().optional(),
                version: z.string().optional(),
                locale: z.string().optional()
            }).nullish()
        }).optional()
    }).optional()
});

export const zGetVehicleImagesData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            extension: z.string(),
            resolution: z.string(),
            vehicleVersion: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'dc-cid': z.string()
    })
});

/**
 * Vehicle images
 */
export const zGetVehicleImagesResponse = z.object({
    data: z.object({
        getVehicleOrderMobileImages: z.array(zVehicleMobileImage).optional(),
        getVehicleMobileImages: z.array(zVehicleMobileImage).optional()
    }).optional()
});

export const zGetEstimatedRangeData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            startSoc: z.number().gte(0).lte(100),
            vehicleId: z.string(),
            driveMode: z.string().optional(),
            trailerProfile: z.string().optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'dc-cid': z.string().optional()
    }).optional()
});

/**
 * Estimated range
 */
export const zGetEstimatedRangeResponse = z.object({
    data: z.object({
        getVehicle: z.object({
            estimatedRange: z.number().optional()
        }).optional()
    }).optional()
});

export const zSetVehicleNameData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            vehicleId: z.string(),
            name: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Name updated
 */
export const zSetVehicleNameResponse = z.object({
    data: z.object({
        setVehicleName: z.object({
            value: z.string().optional()
        }).optional()
    }).optional()
});

export const zSupportedFeaturesData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Supported features
 */
export const zSupportedFeaturesResponse = z.object({
    data: z.object({
        currentUser: z.object({
            vehicles: z.array(z.object({
                id: z.string().optional(),
                vehicle: z.object({
                    vehicleState: z.object({
                        supportedFeatures: z.array(zSupportedFeature).optional()
                    }).optional()
                }).optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zRegisterPushNotificationTokenData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            data: z.object({
                locale: z.string(),
                token: z.string(),
                type: z.enum(['FCM']),
                userId: z.string(),
                mobileApp: z.string()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Token registered
 */
export const zRegisterPushNotificationTokenResponse = z.object({
    data: z.object({
        registerPushNotificationToken: z.object({
            deviceTokenId: z.string().optional(),
            locale: z.string().optional(),
            success: z.boolean().optional(),
            token: z.string().optional()
        }).optional()
    }).optional()
});

export const zGetVehicleWheelImageData = z.object({
    body: z.never().optional(),
    path: z.object({
        wheelOption: z.string()
    }),
    query: z.never().optional()
});

/**
 * Wheel image
 */
export const zGetVehicleWheelImageResponse = z.string();

export const zVehicleSubscriptionsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'a-sess': z.string(),
        'u-sess': z.string(),
        'csrf-token': z.string()
    })
});

export const zPlacesData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            params: z.object({
                userLocation: z.object({
                    latitude: z.number().optional(),
                    longitude: z.number().optional()
                }).optional(),
                query: z.string()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Place results
 */
export const zPlacesResponse = z.object({
    data: z.object({
        places: z.object({
            dataProvider: z.string().optional(),
            results: z.array(zPlaceResult).optional()
        }).optional()
    }).optional()
});

export const zPlanTripData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            waypoints: z.array(z.object({
                latitude: z.number(),
                longitude: z.number(),
                entityId: z.string().optional(),
                waypointType: z.enum(['OTHER', 'DC_CHARGE_STATION'])
            })),
            originBearing: z.number(),
            vehicleId: z.string(),
            startingSoc: z.number(),
            startingRangeMeters: z.number().optional(),
            targetArrivalSocPercent: z.number().optional(),
            driveMode: z.enum([
                'EVERYDAY',
                'SPORT',
                'CONSERVE'
            ]).optional(),
            networkPreferences: z.array(z.object({
                networkId: z.string().optional(),
                preference: z.number().int().optional()
            })).optional(),
            trailerProfile: z.enum(['NONE']).optional(),
            avoidAdapterRequired: z.boolean().optional(),
            supportedConnectorTypes: z.array(z.enum(['CCS', 'J1772'])).optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Trip plan
 */
export const zPlanTripResponse = z.object({
    data: z.object({
        planTripMultiStop: zTripPlanResult.optional()
    }).optional()
});

export const zSaveTripData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            attrs: z.object({
                name: z.string(),
                startingSOC: z.number(),
                stops: z.array(z.object({
                    name: z.string().optional(),
                    location: z.object({
                        latitude: z.number().optional(),
                        longitude: z.number().optional()
                    }).optional(),
                    targetArrivalSOCPercent: z.number().optional(),
                    type: z.enum(['VEHICLE_LOCATION', 'POI']).optional(),
                    placeId: z.object({
                        value: z.string().optional(),
                        dataProvider: z.string().optional()
                    }).optional()
                })),
                driveMode: z.string().optional(),
                networkPreferences: z.array(z.object({
                    networkId: z.string().optional(),
                    preference: z.number().int().optional()
                })).optional(),
                trailerProfile: z.string().optional(),
                avoidAdapterRequired: z.boolean().optional(),
                departureTime: z.number().int().optional()
            })
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Trip saved
 */
export const zSaveTripResponse = z.object({
    data: z.object({
        saveTrip: z.string().optional()
    }).optional()
});

export const zGetSavedTripsData = z.object({
    body: zGraphQlRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Saved trips
 */
export const zGetSavedTripsResponse = z.object({
    data: z.object({
        getSavedTrips: z.array(z.object({
            id: z.string().optional(),
            name: z.string().optional(),
            startingSOC: z.number().optional(),
            stops: z.array(z.object({
                name: z.string().optional(),
                location: z.object({
                    latitude: z.number().optional(),
                    longitude: z.number().optional()
                }).optional(),
                targetArrivalSOCPercent: z.number().optional(),
                type: z.string().optional(),
                placeId: z.object({
                    value: z.string().optional(),
                    dataProvider: z.string().optional()
                }).optional()
            })).optional(),
            driveMode: z.string().optional(),
            networkPreferences: z.array(z.object({
                networkId: z.string().optional(),
                preference: z.string().optional()
            })).optional(),
            trailerProfile: z.string().optional(),
            avoidAdapterRequired: z.boolean().optional(),
            createdAt: z.string().optional(),
            updatedAt: z.string().optional(),
            departureTime: z.string().optional()
        })).optional()
    }).optional()
});

export const zGetTrailerProfilesData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            getVehicleId: z.string()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Trailer profiles
 */
export const zGetTrailerProfilesResponse = z.object({
    data: z.object({
        getVehicle: z.object({
            trailerProfiles: z.object({
                trailerDefault: zTrailerProfile.optional(),
                trailer1: zTrailerProfile.optional(),
                trailer2: zTrailerProfile.optional(),
                trailer3: zTrailerProfile.optional()
            }).nullish()
        }).optional()
    }).optional()
});

export const zSearchShopProductsBySkusData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            country: z.string().optional().default('US'),
            skus: z.array(z.string()),
            pageInfo: z.object({
                from: z.number().int().optional(),
                size: z.number().int().optional()
            }).optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'csrf-token': z.string().optional(),
        'dc-cid': z.string().optional(),
        'x-datadog-origin': z.string().optional()
    }).optional()
});

/**
 * Product search results
 */
export const zSearchShopProductsBySkusResponse = z.object({
    data: z.object({
        searchProducts: z.object({
            total: z.number().int().optional(),
            size: z.number().int().optional(),
            from: z.number().int().optional(),
            data: z.array(z.object({
                sku: z.string().optional(),
                title: z.string().optional(),
                brand: z.string().optional(),
                rivianShopStatus: z.string().optional(),
                price: z.object({
                    listPrice: z.object({
                        amount: z.number().optional(),
                        currency: z.string().optional()
                    }).optional()
                }).optional(),
                dimensionValues: z.array(z.object({
                    name: z.string().optional(),
                    valueName: z.string().optional(),
                    localizedStrings: z.string().optional()
                })).optional(),
                channels: z.array(z.record(z.unknown())).optional(),
                channelAttributes: z.array(z.object({
                    attributeId: z.string().optional(),
                    name: z.string().optional(),
                    channel: z.string().optional(),
                    value: z.string().optional()
                })).optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zSearchShopPricingBySkuData = z.object({
    body: z.object({
        operationName: z.string().optional(),
        variables: z.object({
            country: z.string().optional().default('US'),
            skus: z.array(z.string()),
            pageInfo: z.object({
                from: z.number().int().optional(),
                size: z.number().int().optional()
            }).optional()
        }).optional(),
        query: z.string().optional()
    }),
    path: z.never().optional(),
    query: z.never().optional(),
    headers: z.object({
        'csrf-token': z.string().optional(),
        'dc-cid': z.string().optional(),
        'x-datadog-origin': z.string().optional()
    }).optional()
});

/**
 * Pricing results
 */
export const zSearchShopPricingBySkuResponse = z.object({
    data: z.object({
        searchProducts: z.object({
            total: z.number().int().optional(),
            size: z.number().int().optional(),
            from: z.number().int().optional(),
            data: z.array(z.object({
                sku: z.string().optional(),
                price: z.object({
                    listPrice: z.object({
                        amount: z.number().optional(),
                        currency: z.string().optional()
                    }).optional()
                }).optional()
            })).optional()
        }).optional()
    }).optional()
});

export const zGetConfiguratorImageData = z.object({
    body: z.never().optional(),
    path: z.object({
        vehicle: z.enum(['r1t', 'r1s']),
        view: z.enum([
            'front',
            'rear',
            'side',
            'driver',
            'backseats',
            'studio'
        ]),
        options: z.string()
    }),
    query: z.never().optional()
});

/**
 * Vehicle configuration image
 */
export const zGetConfiguratorImageResponse = z.string();
